### ISSUE TITLE
Abricate CARD and CARD website gives different results!

### ISSUE THREAD

**Issue by mmaesaar** [tseemann/abricate#100]
I was analyzing fasta file containing contigs with abricate using CARD db and got the following results:
*coverage 100%
*identity 99.53%

Then ran same file using CARD website and got slightly different result for the same gene:
*coverage 100%
*identity 99.05%

Is this expected result or should they match?

**Comment by mmaesaar** [comment]
I just found out that website version uses Diamond not BLAST.

**Comment by tseemann** [comment]
Abricate uses DNA matching.
CARD/RGI uses Protein matching.
They can't be compared.

I will endeavour to make this clear in the documentation.
