### ISSUE TITLE
typo in readme regarding Path::Tiny perl module install on ubuntu

### ISSUE THREAD

**Issue by kapsakcj** [tseemann/abricate#102]
Hi Torsten,

I believe there's a typo in https://github.com/tseemann/abricate#source for installing perl modules on Ubuntu.

I was getting this error while building a docker container for abricate 0.9.7 in a Ubuntu:xenial based container: `Can't locate Path/Tiny.pm in @INC (you may need to install the Path::Tiny module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.22.1 /usr/local/share/perl/5.22.1 /usr/lib/x86_64-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at /abricate-0.9.7/bin/abricate line 7.`

This line:

`sudo apt-get install libfile-path-tiny`

should be: 

`sudo apt-get install libpath-tiny-perl`

```
$ sudo apt-get install libfile-path-tiny
E: Unable to locate package libfile-path-tiny

$ sudo apt-get install libpath-tiny-perl
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  libpath-tiny-perl
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 49.8 kB of archives.
After this operation, 145 kB of additional disk space will be used.
Get:1 http://us.archive.ubuntu.com/ubuntu xenial/universe amd64 libpath-tiny-perl all 0.076-1 [49.8 kB]
Fetched 49.8 kB in 0s (368 kB/s)
Selecting previously unselected package libpath-tiny-perl.
(Reading database ... 279410 files and directories currently installed.)
Preparing to unpack .../libpath-tiny-perl_0.076-1_all.deb ...
Unpacking libpath-tiny-perl (0.076-1) ...
Processing triggers for man-db (2.7.5-1) ...
Setting up libpath-tiny-perl (0.076-1) ...
```
This allowed for the container to be built successfully, abricate test (`abricate test/assembly.fa`) ran as expected, and the perl module error message went away.

**Comment by tseemann** [comment]
Thanks @kapsakcj !
