### ISSUE TITLE
Coverage and identity of hit

### ISSUE THREAD

**Issue by nbawe** [tseemann/abricate#104]
I have a question. I am getting quite a many hits using abricate default of coverage and identity. 

What should one consider as a confident hit regarding coverage and identity parameters. Is 95% coverage and 95% identity too strict for gene hits of the same species?

**Comment by tseemann** [comment]
It depends on 

* the scientific question you are trying to answer
* which `--db` you are using

Tips:

* Protein identity is probably more important so don't be too strict on the DNA identity parameter.
* Coverage default 0% is not good if you are looking for real genes, so increasing it to a high value it probably smart. But if your genome assembly is poor and there are paralogs or the middle of gene has extreme GC (bad coverage on Illumina) then the gene will appear in 2 parts and 95% coverage means you will miss it.   Try 50% and see how you go.

**Comment by nbawe** [comment]
Thank you for the clarification.

**Comment by hites77** [comment]
I have a similar scenario. I found that Abricate (vfdb) predict 0 hits for a staphylococcus genome while VFDB webserver (with gbk file) listed several virulence genes. So, I ran it with different coverage and identity and found it gives hits with lower values.
So, my question is what can be the minimum identity and coverage which might be scientifically correct?
