### ISSUE TITLE
unsatisfied perl dependencies

### ISSUE THREAD

**Issue by mbprentice** [tseemann/abricate#11]
Hi Torsten

I couldn't install abricate via linuxbrew, any advice gratefully received, thanks

`brew install abricate --HEAD`
==> Installing abricate from tseemann/bioinformatics-linux
abricate: Unsatisfied dependency: File::Slurp
Homebrew does not provide special Perl dependencies; install with:
  `cpan -i File::Slurp`
abricate: Unsatisfied dependency: Text::CSV
Homebrew does not provide special Perl dependencies; install with:
  `cpan -i Text::CSV`
abricate: Unsatisfied dependency: JSON
Homebrew does not provide special Perl dependencies; install with:
  `cpan -i JSON`
Error: Unsatisfied requirements failed this build.

I tried `cpan -i File::Slurp`  with no effect on abricate installation

Loading internal null logger. Install Log::Log4perl for logging messages

CPAN.pm requires configuration, but most of it can be done automatically.
If you answer 'no' below, you will enter an interactive dialog for each
configuration option instead.

Would you like to configure as much as possible automatically? [yes] yes
Use of uninitialized value $what in concatenation (.) or string at /usr/share/perl/5.22/App/Cpan.pm line 633, <STDIN> line 1.

Warning: You do not have write permission for Perl library directories.

To install modules, you need to configure a local Perl library directory or
escalate your privileges.  CPAN can help you by bootstrapping the local::lib
module or by configuring itself to use 'sudo' (if available).  You may also
resolve this problem manually if you need to customize your setup.

What approach do you want?  (Choose 'local::lib', 'sudo' or 'manual')
 [local::lib] local::lib
Attempting to create directory /home/mike/perl5

Checking if your kit is complete...
Looks good
Generating a Unix-style Makefile
Writing Makefile for local::lib
Writing MYMETA.yml and MYMETA.json
cp lib/POD2/DE/local/lib.pod blib/lib/POD2/DE/local/lib.pod
cp lib/POD2/PT_BR/local/lib.pod blib/lib/POD2/PT_BR/local/lib.pod
cp lib/local/lib.pm blib/lib/local/lib.pm
cp lib/lib/core/only.pm blib/lib/lib/core/only.pm
Manifying 4 pod documents
PERL_DL_NONLAZY=1 "/usr/bin/perl" "-I/home/mike/perl5/lib/perl5" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/bad_variables.t ...... ok   
t/carp-mismatch.t ...... ok   
t/classmethod.t ........ ok   
t/coderefs_in_inc.t .... ok   
t/de-dup.t ............. ok   
t/lib-core-only.t ...... ok   
t/pipeline.t ........... ok   
t/shell.t .............. ok     
t/stackable.t .......... ok     
t/subroutine-in-inc.t .. ok   
t/taint-mode.t ......... ok   
All tests successful.
Files=11, Tests=149,  2 wallclock secs ( 0.05 usr  0.01 sys +  0.94 cusr  0.06 csys =  1.06 CPU)
Result: PASS
Manifying 4 pod documents
Installing /home/mike/perl5/lib/perl5/POD2/PT_BR/local/lib.pod
Installing /home/mike/perl5/lib/perl5/POD2/DE/local/lib.pod
Installing /home/mike/perl5/lib/perl5/lib/core/only.pm
Installing /home/mike/perl5/lib/perl5/local/lib.pm
Installing /home/mike/perl5/man/man3/POD2::DE::local::lib.3pm
Installing /home/mike/perl5/man/man3/POD2::PT_BR::local::lib.3pm
Installing /home/mike/perl5/man/man3/lib::core::only.3pm
Installing /home/mike/perl5/man/man3/local::lib.3pm
Appending installation info to /home/mike/perl5/lib/perl5/x86_64-linux-gnu-thread-multi/perllocal.pod

Would you like me to append that to /home/mike/.bashrc now? [yes] yes
Running install for module 'File::Slurp'
Fetching with LWP:
http://www.cpan.org/authors/id/U/UR/URI/File-Slurp-9999.19.tar.gz
Fetching with LWP:
http://www.cpan.org/authors/id/U/UR/URI/CHECKSUMS
Checksum for /home/mike/.cpan/sources/authors/id/U/UR/URI/File-Slurp-9999.19.tar.gz ok
Configuring U/UR/URI/File-Slurp-9999.19.tar.gz with Makefile.PL
Checking if your kit is complete...
Looks good
Generating a Unix-style Makefile
Writing Makefile for File::Slurp
Writing MYMETA.yml and MYMETA.json
  URI/File-Slurp-9999.19.tar.gz
  /usr/bin/perl Makefile.PL INSTALLDIRS=site -- OK
Running make for U/UR/URI/File-Slurp-9999.19.tar.gz
cp lib/File/Slurp.pm blib/lib/File/Slurp.pm
Manifying 1 pod document
  URI/File-Slurp-9999.19.tar.gz
  /usr/bin/make -- OK
Running make test
PERL_DL_NONLAZY=1 "/usr/bin/perl" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/append_null.t ....... ok   
t/binmode.t ........... ok   
t/chomp.t ............. ok   
t/data_list.t ......... ok   
t/data_scalar.t ....... ok   
t/edit_file.t ......... ok   
t/error.t ............. ok     
t/error_mode.t ........ ok   
t/file_object.t ....... ok   
t/handle.t ............ ok   
t/inode.t ............. ok   
t/large.t ............. ok       
t/newline.t ........... ok   
t/no_clobber.t ........ ok   
t/original.t .......... ok   
t/paragraph.t ......... ok     
t/perms.t ............. ok   
t/pod.t ............... skipped: Test::Pod 1.14 required for testing POD
t/pod_coverage.t ...... skipped: Test::Pod::Coverage 1.04 required for testing POD coverage
t/prepend_file.t ...... ok   
t/pseudo.t ............ ok   
t/read_dir.t .......... ok   
t/signal.t ............ ok   
t/slurp.t ............. ok   
t/stdin.t ............. ok   
t/stringify.t ......... ok   
t/tainted.t ........... ok   
t/write_file_win32.t .. ok   
All tests successful.
Files=28, Tests=296,  3 wallclock secs ( 0.07 usr  0.02 sys +  0.72 cusr  0.05 csys =  0.86 CPU)
Result: PASS
  URI/File-Slurp-9999.19.tar.gz
  /usr/bin/make test -- OK
Running make install
Manifying 1 pod document
Installing /home/mike/perl5/lib/perl5/File/Slurp.pm
Installing /home/mike/perl5/man/man3/File::Slurp.3pm
Appending installation info to /home/mike/perl5/lib/perl5/x86_64-linux-gnu-thread-multi/perllocal.pod
  URI/File-Slurp-9999.19.tar.gz
  /usr/bin/make install  -- OK

`brew install abricate --HEAD`

==> Installing abricate from tseemann/bioinformatics-linux
abricate: Unsatisfied dependency: File::Slurp etc etc

`brew doctor`
Your system is ready to brew
`brew update`
Already up-to-date

 `brew config`
HOMEBREW_VERSION: 1.1.10
ORIGIN: https://github.com/Linuxbrew/brew.git
HEAD: d8c8b867bf99c604c89bc848f58d1fae8afd599c
Last commit: 5 weeks ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: 9f0d64e6326d616c0c2ceb996d1903b6ae456aec
Core tap last commit: 4 days ago
HOMEBREW_PREFIX: /home/mike/.linuxbrew
HOMEBREW_REPOSITORY: /home/mike/.linuxbrew
HOMEBREW_CELLAR: /home/mike/.linuxbrew/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://linuxbrew.bintray.com
CPU: quad-core 64-bit 0x65e
Homebrew Ruby: 2.3.1 => /usr/bin/ruby2.3
Clang: N/A
Git: 2.7.4 => /usr/bin/git
Perl: /usr/bin/perl
Python: /home/mike/.linuxbrew/bin/python => /home/mike/.linuxbrew/Cellar/python/2.7.13/bin/python2.7
Ruby: /usr/bin/ruby => /usr/bin/ruby2.3
Java: 1.8.0_112
Kernel: Linux 4.4.0-53-generic x86_64 GNU/Linux
OS: Ubuntu 16.04.1 LTS
Codename: xenial
OS glibc: 2.23
OS gcc: 5.4.0
Linuxbrew glibc: N/A
Linuxbrew gcc: 5.3.0
Linuxbrew xorg: N/A

**Comment by tseemann** [comment]
It seems you have set up Perl in `local::lib` mode.  For this to work you need to add some environment variables to your `.bashrc` to tell it where you are installing Perl modules (in your home directory somewhere).

For example, here is mine: 
```
export PERL_LOCAL_LIB_ROOT=/bio/perl5:/home/tseemann/perl5
```
