### ISSUE TITLE
Changes in ARO relationship names

### ISSUE THREAD

**Issue by arpcard** [tseemann/abricate#110]
CARD has updated some terminology in the Antibiotic Resistance Ontology:

confers_resistance_to changed to **confers_resistance_to_drug_class**

confers_resistance_to_drug changed to **confers_resistance_to_antibiotic**

targeted_by_drug changed to **targeted_by_antibiotic**

These changes affect the ontology download files (i.e. https://card.mcmaster.ca/latest/ontology) but do not result in any format/content changes in the CARD data downloads (https://card.mcmaster.ca/latest/data).

**Comment by tseemann** [comment]
Appreciate the warning!
I have checked over my code and I don't use those fields but maybe I should be.
I currently use:
```
    for my $key (keys $g->{ARO_category}->%*) {
      my $c = $g->{ARO_category}{$key};
      if ($c->{category_aro_class_name} eq 'Drug Class') {
        my $abx = $c->{category_aro_name};
      if ($c->{category_aro_class_name} eq 'AMR Gene Family') {
    #err("CARD | $id | ", Dumper($g->{ARO_category}) ) unless $is_amr_gene;
      DESC => ($g->{ARO_description} || $g->{ARO_accession}),
```

**Comment by tseemann** [comment]
UPDATE: i only use `card.json` download; i misread the last part of your message. I am not affected. Thank you!

**Comment by arpcard** [comment]
Note:

* curation of *AMR Gene Family* confers_resistance_to_drug_class *Drug Class* is heavily curated, enforced at the curation interface, and checked by QC

* curation of a particular *gene/mutation* confers_resistance_to_antibiotic a particular *antibiotic* is ongoing and incomplete
