### ISSUE TITLE
Path::Tiny 

### ISSUE THREAD

**Issue by drahmadghazi** [tseemann/abricate#112]
HI, I'm getting this: 

Can't locate Path/Tiny.pm in @INC (you may need to install the Path::Tiny module) (@INC contains: /home/drahmadghazi/miniconda3/lib/site_perl/5.26.2/x86_64-linux-thread-multi /home/drahmadghazi/miniconda3/lib/site_perl/5.26.2 /home/drahmadghazi/miniconda3/lib/5.26.2/x86_64-linux-thread-multi /home/drahmadghazi/miniconda3/lib/5.26.2 .) at ./abricate line 7.
BEGIN failed--compilation aborted at ./abricate line 7.

I have already installed the dependencies and still getting this error. 

Please Help!

**Comment by tseemann** [comment]
Looks like your conda env is broken.

```
conda update --all
```
then
```
conda create -n abricate_env  -c conda-forge -c bioconda -c defaults abricate
conda activate abricate
abricate --version
abricate --check
```

**Comment by drahmadghazi** [comment]
Thanks so much, working now,
Is there a way to export the data into a file?

**Comment by tseemann** [comment]
You mean using standard Unix redirect?
```
abricate contigs.fa > results.tab
```

**Comment by Luponsky** [comment]
Dear @tseemann thanks for developing this tool,
Unfortunately I can't be able to use it.
I'm working on a server, and I'm following the installation with conda.
The installation goes well, then when I run abricate --version I get the aforementioned problem

(abricate_env) [LAPO@podmt2-b2ae0 ~]$ abricate --version
Can't locate Path/Tiny.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /home/LAPO/miniconda3/envs/abricate_env/bin/abricate line 7.
BEGIN failed--compilation aborted at /home/LAPO/miniconda3/envs/abricate_env/bin/abricate line 7.

I get the same error also when I run abricate --check

I tried to update the packages, as you suggested, but they are already updated, thus this doesn't solve anything and  I got the same error.

Hope you can help me,

Cheers

**Comment by ewissel** [comment]
As of 2021/7/26 I am still encountering this bug. The proposed fix above does not work for me. I had a conda env work for abricate a few months ago, now running into this issue. Appreciate any suggestions!

**Comment by mars188** [comment]
I successfully ran abricate few months ago but now getting the same error mentioned above. Please help

**Comment by melinarosy** [comment]
Hi everyone, 
I tried to use this amazing tool and I run into the same problem you have. I tried to export path to the location the program was installed using this line in ubuntu:
export PERL5LIB=/usr/local/lib/x86_64-linux-gnu/perl/5.34.0/auto/

then, I tried installing the program with conda using this command:
conda install -c bioconda perl-path-tiny

Then, it asked for the path of another program called list-moreutils and I used the same trick to saolve that:
conda install -c bioconda perl-list-moreutils

**Comment by evagrash** [comment]
Hi all, I was facing the same issue. In my case, the system Perl was being used instead of the Conda environment one. My issue was solved by defining the path to the correct Perl:

export PATH="$CONDA_PREFIX/bin:$PATH"
