### ISSUE TITLE
Genes lost in --summary

### ISSUE THREAD

**Issue by sxh1136** [tseemann/abricate#114]
Hi there,

I ran a two samples through abricate using CARD and got 300+ gene hits. When I combine the results with --summary it only shows 64 and 55 hits.

Is there a flag I'm missing or a maximum number of hits --summary can show?

**Comment by tseemann** [comment]
What version of abricate are you using?   Run `abricate --version`. Hopefully >= 0.9.8

If you get lots of paralog/duplicate genes with the same ID, they will probably be merged in the summary. I am astounded you could get 300 hits in one genome. I'm guessing these are metagenomic assemblies.

Please upload or email me your output tables if you need further help.

**Comment by sxh1136** [comment]
Yeh they are metagenomic assemblies and it looks like I accidentally concatenated multiple samples. It works fine now, thanks!
