### ISSUE TITLE
Abricate stops when finding contigs starting with NNNNN

### ISSUE THREAD

**Issue by dutchscientist** [tseemann/abricate#115]
I am working with some poorly assembled genomes downloaded from PubMLST, and Abricate stops when it encounters contigs starting with N's:

abricate --db ncbi --minid 75 --mincov 70 --threads 7 jejuni40001/Cj44978p_0021_76262.fna > test_ncbi_abricate.tsv
Using nucl database ncbi:  5029 sequences -  2019-Oct-6
Processing: jejuni40001/Cj44978p_0021_76262.fna
ERROR: can not find sequence data in 'jejuni40001/Cj44978p_0021_76262.fna'

This is the first contig bit of the assembly:
```
>2633872|65_38345_denovo
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNCCTTCTCCAKGGGATTTTCCC
AACCCAGGGATCNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
>2633873|7_38345_denovo
GATTTTTAAGAGTGCTTTCATATAGTGAGGTTTTTGTAAAATAAAAACTTACAATACCTA
GAACAATTAAGGCAAAAATTGCAATTAAATTTGCAATGAGGGAAAGTTTGATTTTAATAC
TATTCATTATTTTCCTTTTAATCTTTGTTATTTTTAGCATAAAACTAATAATTTGGCTAT
TATTTTATCACAAAAAAATAAAATAAATTTTTATTTTTATCTTAAATAAAGGAGAAAATA
TGGCTTATACTATAAAAAAAGTAGAAAAAGAAACAAAAGTTAGTGCTCATACTTTAAGAT
TTTGGGCTAAAAAAGGTTTGTTTCCTTTTGTTCAAAAAGATGAAAATAGTGTGAAATATT
```
Assembly is available on https://pubmlst.org/bigsdb?db=pubmlst_campylobacter_isolates&page=downloadSeqbin&isolate_id=76154
N50, L50 etc stats are OK, although that may be due to the N's.

Problem is that abricate crashes out on this, and hence does not continue the rest of the genomes in the folder. Can it be set to ignore it or leave a logfile with failed sequences, or even better, just ignore that it is a bad quality genome and still search it?

**Comment by mmaesaar** [comment]
Thank you @dutchscientist! I posted in issue #99. Then I did not get the bottom of it! But the reason is same as you posted here.

**Comment by dutchscientist** [comment]
Thanks for the cross-link, had missed that one.

I have checked whether it is the | symbol by using sed to replace them with _, and that's not the problem. Have tried to remove the N's but that does lead to empty contigs, which seems to be problematic as well.

I have had a look at a few of the problem cases, and I will throw the whole collection out. Such bad assemblies they should not be in a database :(

**Comment by tseemann** [comment]
Yes I confirm I get the following error message:

```
% abricate --version
abricate 0.9.8

% seqkit  stats abricate-issue_115.fna
file                    format  type  num_seqs    sum_len  min_len   avg_len  max_len
abricate-issue_115.fna  FASTA   DNA         90  1,710,504      380  19,005.6  428,054

%  abricate abricate-issue_115.fna
Using nucl database ncbi:  5029 sequences -  2019-Sep-7
#FILE   SEQUENCE        START   END     STRAND  GENE    COVERAGE        COVERAGE_MAP    GAPS    %COVERAGE      %IDENTITY       DATABASE        ACCESSION       PRODUCT RESISTANCE
Processing: abricate-issue_115.fna
ERROR: can not find sequence data in 'abricate-issue_115.fna'
```

That error occurs when the BLAST command returns no header in the TSV output.

**Comment by tseemann** [comment]
This bug has been fixed and will be released in v0.9.9.

You can patch the `abricate` perl file as follows to make it work now:
```
 #          . " -max_target_seqs ".$dbinfo->{SEQUENCES}   # Issue #76
-          . ") 2>&1"
+          . ")"
```
This will give this:
```
Found 2 genes in abricate-issue_115.fna
abricate-issue_115.fna  2633883|10_38345_denovo 42781   44700   -       tet(O)  1-1920/1920     ===============        0/0     100.00  99.64   ncbi    NG_048264.1     tetracycline resistance ribosomal protection protein Tet(O)    TETRACYCLINE
abricate-issue_115.fna  2633909|5_38345_denovo  40668   41473   +       blaOXA-605      1-807/807     ========/======  1/1     99.88   99.63   ncbi    NG_057542.1     OXA-61 family class D beta-lactamase OXA-605   BETA-LACTAM
```

**Comment by dutchscientist** [comment]
Excellent! 

I had in the end 62 genomes failing, all from the same uploaders, so they may not be good at genome assembly... But as I have >44,000 others in the same dataset, it is not that problematic; only reason to keep them in is to get more geographic variability.

Will give it a shot with the edited perl file this week :)

**Comment by tseemann** [comment]
I have informed BigsDB @kjolley about the assembly.

**Comment by dutchscientist** [comment]
I can give him all the IDs if he wants me to,

**Comment by dutchscientist** [comment]
I am not sure github displays the necessary edits in the perl file correctly? I get error messages, probably semi-colons etc missing?

A copy-paste doesn't work.

**Comment by tseemann** [comment]
Just remove the `2>&1` from `abricate` file.   The thing i pasted is standard Unix `diff` syntax sorry.

**Comment by dutchscientist** [comment]
Ah, that works. It warns me during running about those genome sequences with:

_Warning: [blastn] Query_76 2635661|36_41150_denovo: Could not calculate ungapped Karlin-Altschul parameters due to an invalid query sequence or its translation. Please verify the query sequence(s) and/or filtering options_

I assume that is for each bad contig. But it reports the resistance genes back, so great!
