### ISSUE TITLE
Issues in abricate results

### ISSUE THREAD

**Issue by tanu121093** [tseemann/abricate#117]
Hi, firstly i congratulate you for developing a wonderful tool. I have used the tool for antibiotic resistance analysis and when i confirmed the results with blast i got some abrupt results. when i performed blast at protein level ( specifically, tblastn), i found the gene which was absent in my strain by abricate analysis, was found to be present in my strain with 58% identity (high enough for protein). example- I have taken the protein sequence of gene blaOXA-23 from NCBI database and have blast it against the assembled sequence of my strain, and i found a 58% identity, 100% query coverage and 5e-104 E value. This gene was found to be absent in my strain by abricate analysis. Please clarify the issue. 
Also, I want to know the cut off values that tool uses for identity and coverage for antibiotic resistance genes.
In addition to this, kindly provide the refseq database which the tool uses.

**Comment by tseemann** [comment]
@tanu121093 

1. thank you

2. abricate does DNA:DNA which will fail at low sequence identity. you solved that by moving to tblastn which is PROT:PROT which has more sensitivity. If you want PROT:PROT all the time you will need to use another tool. i recommened AMRFinderPlus from NCBI.

3. the cutoff values are in the `--help`
```
FILTERING
  --minid [n.n]   Minimum DNA %identity [75].
  --mincov [n.n]  Minimum DNA %coverage [0].
```

4. the databases are described in the documentation, and i don't know which one you chose via `--db`. See https://github.com/tseemann/abricate#citation
