### ISSUE TITLE
what does this "/" in coverage_map mean?

### ISSUE THREAD

**Issue by wn835166087** [tseemann/abricate#118]
Hi,
 I got the coverage map of each contigs but I had no idea what does it mean... I assume "=" means aligned area while "..." means unaligned. But what does the "/" mean?
Thank you!

best,
nan

**Comment by tseemann** [comment]
Thank you for sending this, I realise that `COVERAGE_MAP` is not properly documented at https://github.com/tseemann/abricate#output - I will fix it.

Yes, `=` is aligned, `.` is unaligned, and `/` means the alignment had some gaps in it. These gaps could be "harmless" (a deleted in-frame codon) or could be damaging (frame-shift).  It was designed as a quick visual aid, but I would like to do more work to properly illustrate what happened to the protein.
