### ISSUE TITLE
blastn analysis shows 98% identity for a gene which is shown to be absent by abricate analysis

### ISSUE THREAD

**Issue by tanu121093** [tseemann/abricate#119]
In individual blastn analysis for genes, I am getting 100% coverage and 98% identity for a gene OXA-51 in strains where abricate analysis summary was showing its absence. Kindly explain this discrepancy in result.

**Comment by pepijnhuizinga** [comment]
Could you supply a little more information, such as what database did you use in both searches. And in the abricate result, is there another gene called in the same region? (check node and location) that is similar to OXA-51.

**Comment by tanu121093** [comment]
i have used ncbi database in both cases. No other gene similar to OXA-51 is present in that strain. The ncbi accession number of gene OXA-51 is same for abricate and blast results.

**Comment by tseemann** [comment]
@tanu121093 are you sure you used the **exact same databases** in your "manual analysis" versus using "abricate" ?

Do you monitor the NBCI database change logs?
eg https://ftp.ncbi.nlm.nih.gov/pathogen/Antimicrobial_resistance/AMRFinder/data/latest/changes.txt

```
           HMM Modified:  NF000268.2 blaOXA-51_like updated to NF000268.2 blaOXA-55_like-NCBI
```

**Comment by tanu121093** [comment]
thank you for the reply.

**Comment by tseemann** [comment]
@tanu121093 you didn't answer any of the questions so I won't be able to help anymore. i hope you resolved the discrepancy.

**Comment by tanu121093** [comment]
i have resolved the problem. There is no issue in results provided by abricate software. Actually, the gene i was looking for(oxa-51), has various forms that are showing 98% identity and abricate has included results for 100% identical forms of gene only. Thank you so much for the reply.
