### ISSUE TITLE
Support for GENBANK, and GZ files?

### ISSUE THREAD

**Issue by andersgs** [tseemann/abricate#12]
It would make it easier to screen Genbank Assemblies.

A.

**Comment by tseemann** [comment]
This is a good idea, it was useful for `mlst`.

**Comment by tseemann** [comment]
Leaving this note here to remind me, consider using EMBOSS:

```
gzip -d -c -f Staphylococcus_epidermidis_ST14.gbk.gz | seqret -auto -filter -osformat2 fasta
```
