### ISSUE TITLE
Updated AMRFinder reference

### ISSUE THREAD

**Issue by linsalrob** [tseemann/abricate#120]
Seems like the NCBI AMRfinder paper was published in [Antimicrobial Agents and Chemotherapy](https://pubmed.ncbi.nlm.nih.gov/31427293-validating-the-amrfinder-tool-and-resistance-gene-database-by-using-antimicrobial-resistance-genotype-phenotype-correlations-in-a-collection-of-isolates/) under a slightly different title than the [bioRxiv](https://www.biorxiv.org/content/10.1101/550707v1) preprint:

*Feldgarden M, Brover V, Haft DH, Prasad AB, Slotta DJ, Tolstoy I, Tyson GH, Zhao S, Hsu C-H, McDermott PF, Tadesse DA, Morales C, Simmons M, Tillman G, Wasilenko J, Folster JP, Klimke W. 2019. Validating the AMRFinder Tool and Resistance Gene Database by Using Antimicrobial Resistance Genotype-Phenotype Correlations in a Collection of Isolates. Antimicrob Agents Chemother 63.*

https://pubmed.ncbi.nlm.nih.gov/31427293-validating-the-amrfinder-tool-and-resistance-gene-database-by-using-antimicrobial-resistance-genotype-phenotype-correlations-in-a-collection-of-isolates/

**Comment by tseemann** [comment]
Thank you @linsalrob !
