### ISSUE TITLE
Add Database Version

### ISSUE THREAD

**Issue by whottel** [tseemann/abricate#121]
The "DATE" field when running '% abricate --list' appears to be the date when the user installed abricate or executed '% abricate-get_db --db some_database --force' Would it be possible to include a field that reports the version/(date of last update) of the individual databases? (e.g. As of writing this the most recent version of ResFinder is dated 2019-10-01)

**Comment by tseemann** [comment]
Yes that would be nice, but it will depend on me finding a way to preserve the original date of the files I use to build my databases, and then using `touch` to modify the file dates on my files.

If you want to manually tweak yours on your system, using 'touch -t xxxxxx -c db/*`

**Comment by whottel** [comment]
Great, thanks for the prompt reply.
