### ISSUE TITLE
Summary tab file

### ISSUE THREAD

**Issue by Batstaph** [tseemann/abricate#122]
I use abricate to run multiple files and in the past have successfully used the --summary option to produce a summary file with all the isolates listed and their gene content tabulated. I now cannot seem to produce this file. The isolate names are not appearing in the left column. Has something changed with this option?

**Comment by tseemann** [comment]
There were changes to `--summary` last year due to bugs.

Some info here: https://github.com/tseemann/abricate/issues/32

You may need to re-run your abricates.
