### ISSUE TITLE
Not the best hit gene

### ISSUE THREAD

**Issue by hbucqp** [tseemann/abricate#125]
Hi,

I found some resistance genes which are actually in a genome could not be found by abricate. It looks like due to the culling-limit parameter.
[https://genesclouds.oss-cn-beijing.aliyuncs.com/FC7889.fa](url)
The genome in the link above actually have the aadA22 gene, while abricate could not found it.

**Comment by tseemann** [comment]
@hbucqp  I downloaded the genome and ran abricate and it found the gene?

```
% wget https://genesclouds.oss-cn-beijing.aliyuncs.com/FC7889.fa

% abricate --quiet FC7889.fa | greUsing nucl database ncbi:  5283 sequences -  2020-Feb-26
p aad

FC7889.fa	contig120|denovo|FC7889	1024	1815	+	aadA22	1-792/792	===============	0/0	100.00	100.00	ncbi	NG_047346.1	ANT(3'')-Ia family aminoglycoside nucleotidyltransferase AadA22	STREPTOMYCIN

% abricate --version
abricate 0.9.9



```
