### ISSUE TITLE
create customized virulence database

### ISSUE THREAD

**Issue by mabouelk** [tseemann/abricate#126]
I am trying to create a custom database, but I could not, can you help me? 

(base) MOHAMEDs-MacBook-Pro:db mohamedabouelkhair$ pwd 
/Users/mohamedabouelkhair/miniconda3/db
(base) MOHAMEDs-MacBook-Pro:db mohamedabouelkhair$ mkdir sp 
(base) MOHAMEDs-MacBook-Pro:db mohamedabouelkhair$ cd sp/
(base) MOHAMEDs-MacBook-Pro:sp mohamedabouelkhair$ cp /Users/mohamedabouelkhair/Downloads/sp.fasta .
(base) MOHAMEDs-MacBook-Pro:sp mohamedabouelkhair$ ls
sp.fasta
(base) MOHAMEDs-MacBook-Pro:sp mohamedabouelkhair$ makeblastdb -in sp.fasta -title sp -dbtype nucl -hash_index

Building a new DB, current time: 03/01/2020 23:30:08
New DB name:   /Users/mohamedabouelkhair/miniconda3/db/sp/sp.fasta
New DB title:  sp
Sequence type: Nucleotide
Keep MBits: T
Maximum file size: 1000000000B
Adding sequences from FASTA; added 3 sequences in 0.00524807 seconds.
(base) MOHAMEDs-MacBook-Pro:sp mohamedabouelkhair$ abricate --list 
DATABASE	SEQUENCES	DBTYPE	DATE
card	2617	nucl	2020-Mar-1
ecoli_vf	2701	nucl	2020-Mar-1
plasmidfinder	460	nucl	2020-Mar-1
ecoh	597	nucl	2020-Mar-1
ncbi	5283	nucl	2020-Mar-1
resfinder	3077	nucl	2020-Mar-1
vfdb	2597	nucl	2020-Mar-1
argannot	2223	nucl	2020-Mar-1
(base) MOHAMEDs-MacBook-Pro:sp mohamedabouelkhair$

**Comment by tseemann** [comment]
Your database needs to be called `sequences` , not 'sp.fa'

**Comment by mabouelk** [comment]
I changed but still not listed. May be I made that format wrong, can you tell me how to do it, do you mean multiple tabs or exactly like that? 

>tinyamr~~~GENE_ID~~~GENE_ACC~~RESISTANCES some description here.

**Comment by tseemann** [comment]
Type this
```
abricate --help |& grep -i data
```
Are you putting it in the correct --dbdir ?

```
DATABASES
  --setupdb       Format all the BLAST databases.
  --list          List included databases.
  --datadir [X]   Databases folder [/home/linuxbrew/.linuxbrew/Cellar/abricate/0.9.9/libexec/db].
  --db [X]        Database to use [ncbi].
```

**Comment by mabouelk** [comment]
Thank you so much, I putted in the correct directory and it worked

**Comment by tseemann** [comment]
Great news!
