### ISSUE TITLE
ABRicate pre-downloaded databases

### ISSUE THREAD

**Issue by mmaesaar** [tseemann/abricate#128]
Hi @tseemann,

I have abricate `v0.9.9` installed using `brew install abricate`, but somehow megares is not displayed in the `--list`. Should the `megares` database come with installation of abricate?

Thank you!

**Comment by dswan** [comment]
I have megares downloaded and installed with 0.9.9.

Have you tried:

**Comment by nbawe** [comment]
Hi thanks for the suggestion, unfortunately it gives me the following error:
```
abricate-get_db --db megares --force
Setting up 'megares' in '/usr/local/Cellar/abricate/0.9.9/libexec/db/megares'
Downloading: https://megares.meglab.org/download/megares_v2.00.zip
Result: 501
Destination: megares.zip
Filesize:  bytes
unzip:  cannot find or open megares.zip, megares.zip.zip or megares.zip.ZIP.
load_fasta: 

------------- EXCEPTION -------------
MSG: file argument provided, but with an undefined value
STACK Bio::SeqIO::new /usr/local/opt/bioperl/libexec/lib/perl5/Bio/SeqIO.pm:399
STACK main::load_fasta /usr/local/Cellar/abricate/0.9.9/libexec/bin/abricate-get_db:726
STACK main::get_megares /usr/local/Cellar/abricate/0.9.9/libexec/bin/abricate-get_db:351
STACK toplevel /usr/local/Cellar/abricate/0.9.9/libexec/bin/abricate-get_db:60
---------------
```

**Comment by nbawe** [comment]
I had the same issue, but for me it gave an error:
```
abricate-get_db --db megares --force
Setting up 'megares' in '/usr/local/Cellar/abricate/0.9.9/libexec/db/megares'
Downloading: https://megares.meglab.org/download/megares_v2.00.zip
Result: 501
Destination: megares.zip
Filesize:  bytes
unzip:  cannot find or open megares.zip, megares.zip.zip or megares.zip.ZIP.
load_fasta: 

------------- EXCEPTION -------------
MSG: file argument provided, but with an undefined value
STACK Bio::SeqIO::new /usr/local/opt/bioperl/libexec/lib/perl5/Bio/SeqIO.pm:399
STACK main::load_fasta /usr/local/Cellar/abricate/0.9.9/libexec/bin/abricate-get_db:726
STACK main::get_megares /usr/local/Cellar/abricate/0.9.9/libexec/bin/abricate-get_db:351
STACK toplevel /usr/local/Cellar/abricate/0.9.9/libexec/bin/abricate-get_db:60
---------------
```

**Comment by tseemann** [comment]
You are getting a 501 HTTP error.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/501

**Comment by tseemann** [comment]
@mmaesaar it seems i forgot to commit the megares database! sorry.
@nbawe i have added checks to tell you when download fails (for whatever reason).

**Comment by mmaesaar** [comment]
Thank you @tseemann now works perfectly.

**Comment by MHassanSaeed** [comment]
Hi,

I tried abricate-get_db --db ncbi --force but come up with following error:

`Downloading: https://ftp.ncbi.nlm.nih.gov/pathogen/Antimicrobial_resistance/AMRFinderPlus/database/latest/AMR_CDS
HTTP Result: 501
Destination: amr_cds.ffn
Filesize:  bytes
Downloading: https://ftp.ncbi.nlm.nih.gov/pathogen/Antimicrobial_resistance/AMRFinderPlus/database/latest/ReferenceGeneCatalog.txt
HTTP Result: 501
Destination: amr_cds.tsv
Filesize:  bytes
**ERROR: Can't read TSV file: amr_cds.tsv**
`
