### ISSUE TITLE
Allow a list of genomes as input

### ISSUE THREAD

**Issue by MSMortensen** [tseemann/abricate#129]
Hi,
My queueing system has a hard limit on how many arguments a job can have. This gives me a problem when working with large datasets (>1000).

Any chance you could make it possible to use a file with a list of genomes as input?
This would also make it easier if genomes are not located together.

Best,
Martin

**Comment by tseemann** [comment]
All Unix systems have a hard limit on the length of the command line, yes.

There are various ways to mitigate this limitation:
* create symlinks in a folder to all the contig files and use those, they will be shorter overall
* break your HPC job into chunks using `xargs` or `parallel`
* use "job arrays" on your HPC (slurm, Torque etc) which is designed for exactly this

Your suggestion is good, and I will add it soon.

**Comment by tseemann** [comment]
I have added a new `--fofn` option to do this.
