### ISSUE TITLE
Error with making vfdb database

### ISSUE THREAD

**Issue by MelanieBaeck** [tseemann/abricate#131]
Hi,

I could not download the vfdb database... 
following error occurs:

```

BLAST Database creation error: Error: Duplicate seq_ids are found: 
LCL|VFDB~~~FIMA~~~

ERROR: Error with makign BLAST database. See /NGStools/miniconda/db/vfdb/src/makeblastdb.log
```

Also, the abricate --list command is not working now anymore:

```
ERROR: Database ncbi is not indexed, please try: abricate --setupdb
root@5e00bb4f18fb:/home/working# abricate --setupdb
Removing old BLAST indices for /NGStools/miniconda/bin/../db/resfinder/sequences
Making nucl BLAST index for /NGStools/miniconda/bin/../db/resfinder/sequences
Removing old BLAST indices for /NGStools/miniconda/bin/../db/plasmidfinder/sequences
Making nucl BLAST index for /NGStools/miniconda/bin/../db/plasmidfinder/sequences
Removing old BLAST indices for /NGStools/miniconda/bin/../db/ecoli_vf/sequences
Making nucl BLAST index for /NGStools/miniconda/bin/../db/ecoli_vf/sequences
Removing old BLAST indices for /NGStools/miniconda/bin/../db/vfdb/sequences
Making nucl BLAST index for /NGStools/miniconda/bin/../db/vfdb/sequences
ERROR: Database vfdb is not indexed, please try: abricate --setupdb
```

Thanks for help!
P.S.: I am using the Docker Image Download version 0.8.0-3 (https://hub.docker.com/r/flowcraft/abricate/tags)

**Comment by tseemann** [comment]
Current version is `abricate 1.0.0` with lots of bugs fixed.
Can you use the VFDB database that comes with abricate?
I can't support 0.8.0-3
CC: @cimendes

**Comment by MelanieBaeck** [comment]
Thanks a lot! I installed the latest version, now its working.

**Comment by cimendes** [comment]
@MelanieBaeck New docker for abricate version 1.0.0 is now available [here](https://hub.docker.com/repository/docker/flowcraft/abricate/tags?page=1 ). (Thanks @tseemann for the headsup!)

**Comment by MelanieBaeck** [comment]
@cimendes Perfect, thank you so much!
