### ISSUE TITLE
Issues in abricate results

### ISSUE THREAD

**Issue by ireneortega** [tseemann/abricate#132]
Hi, thanks for developing this tool. I have some problems related to ABRicate results. I have used ResFinder db to look for Antibiotic Resistance genes in my genome, but the best hit gene does not appear in ABRicate (default settings used). It founds blaOXA-193_1 with 100 % query cover and 99,61 % identity. But, if I do BLASTn it gives me the gene blaOXA-461 with 100 % query cover and 100 % identity. And this gen is present in the ResFinder db of ABRicate when I run it. I do not understand this discrepancy.

I was wondering if DNA:DNA alignment is the best approach as a single nucleotide mutation can change the protein sequence. Don't you think PROT:DNA alignment will give more reliable results? In that case, could you recommend me a PROT:DNA tool?

Thanks for you help!

**Comment by tseemann** [comment]
If you want to do PROT:DNA please use AMRFinderPlus from NCBI.
