### ISSUE TITLE
Different results with the last version

### ISSUE THREAD

**Issue by Julie-bio** [tseemann/abricate#133]
Hi,

I am using my own data base to find several genes in a single genome.
With the exact same files I used to find more than 2000 genes in this genomes (in December 2019) and not only 500. Is there a new coverage setting option to specify? 

Thank you,

Julie

**Comment by tseemann** [comment]
https://github.com/tseemann/abricate/releases/tag/v1.0.0

Yes the defaults were changed in the 1.0 release.

Please read the change log at the above link.
