### ISSUE TITLE
abricate and prokka

### ISSUE THREAD

**Issue by SumeetTiwari07** [tseemann/abricate#136]
Hi,
I wrote a python script which converts the abricate output to the binary gene presence absence matrix.
Then later i have decided the extended the same script to extract the sequences for those genes from the respective genomes. In the process i have found that some AMR gene reported to be present by abricate in the genome is absent in the output of prokka (.gff3 ) file. I didn't understand why this happened ? is there any specific reason behind this?

**Comment by tseemann** [comment]
@SumeetTiwari07 did you consider using the `abricate --summary` command first?

**Comment by SumeetTiwari07** [comment]
Thank you !! i understood the reason now. 

Yes i tried the summary command but it will gives the identity of the gene in the columns where i wanted to have 0 and 1 indication and another file giving me the exact the number of the genes in same format as produced by _abricate --summary._  
Now my script is working fine. 

Thank you once again
