### ISSUE TITLE
improved docs on summary table

### ISSUE THREAD

**Issue by nick-youngblut** [tseemann/abricate#138]
The README doesn't seem to explain the scores in the summary table (`abricate --summary`), and I can't really tell if it's `percent identity`, `percent coverage`, or something else based on the code https://github.com/tseemann/abricate/blob/master/bin/abricate. It would be helpful to make it clear what those values are

**Comment by tseemann** [comment]
Nick, you have a very good point.  
I'm not even sure what they are myself.
According to the code it is `%COVERAGE`.
I will improve the docs.
Thank you!

**Comment by tseemann** [comment]
Now in https://github.com/tseemann/abricate#combining-reports-across-samples
