### ISSUE TITLE
Can not find sequence data?

### ISSUE THREAD

**Issue by buihoangphuc412** [tseemann/abricate#145]
When I input fasta into Abricate, I can not get any sequence? Do you know what problem?
 abricate --db xerT VN0511_Unicycler.fasta > xerT.tab
Using database xerT:  4 sequences -  May 19, 2020
Processing: VN0511_Unicycler.fasta
WARNING: can not find sequence data in 'VN0511_Unicycler.fasta'
Thank you very much

**Comment by tseemann** [comment]
What does this say:
```
cat -vet VN0511_Unicycler.fasta  | head -n 10
```

**Comment by buihoangphuc412** [comment]
>1 length=392611 depth=1.00x$
AACACACCCTTAGAACTTACTAGAAACTCGCATGATAACTTACAGCTAGAGCCAAAGAACTTCCAGCTCA$
TTTCATAAGAACTTGTAGCTAATGCTAAAGTAATGAAATTATTTTTTAAGCTTTTGTTTAAAAAGTTTGT$
GTTATATTTCCAAATGATTTTTAATTGAATTTAACTTATGTCATAAAACTTAGAGAACGCTTAAAACTTA$
CATTCTTATGATGAAAGCTTGAATTTAGCCAAAAAGCATTGCGTTAAAAATTGCAAGAAAGCTTTACAAG$
ATTTTACAGAAAAAATCAAAGAATCCCCTAATGATTTGAACGCTATGAACGAGACTTTTAATAACTTGGA$
AACAGAGTTAGAGCGCGTTACAGAAAATTTGAGCCAAAAAACAGCGCCCATCTTAGAGCGGTATGAAGAT$
GATAAGCAGCAAGCGTTGGGTTATGGCGAGTTTTTAGAAAAAGAAAAAGAGGGTTTTATTGTAGATGGGC$
AAAACCCCTATCCAGAAGAAGTCCGCTTTAATGAGTTGCGTTTAGCGGAGTTTGATAGCGTTTTTAGCGT$
CATTGTGCCTTTAGAGGATTTAGACCAAACCTGCATGCGCTCATCATGCCCTAAAGGCTTTAGAAGCCGC$

**Comment by tseemann** [comment]
Are you on Mac or Windows ?

**Comment by buihoangphuc412** [comment]
I used Windows and performed on the local server.
seqkit stats VN0511_Unicycler.fasta
file                    format  type  num_seqs    sum_len  min_len   avg_len  max_len
VN0511_Unicycler.fasta  FASTA   DNA         58  1,640,848      117  28,290.5  392,611
Last week Abricate worked well but this problem happened today.

**Comment by tseemann** [comment]
If it worked last week but doesn't now, it sounds like something has changed on your server?
Did you upgrade anything?

Abricate uses `any2fasta` to clean the file. 
Maybe that is breaking it.
Does this work?

```
any2fasta -q -u VN0511_Unicycler.fasta | seqkit stats

``

**Comment by tseemann** [comment]
UPDATE:  that message could mean blast is not working or installed properly!

```
    @x == @BLAST_FIELDS or err("can not find sequence data in '$file'");
```

**Comment by buihoangphuc412** [comment]
any2fasta -q -u VN0511_Unicycler.fasta | seqkit stats
file  format  type  num_seqs    sum_len  min_len   avg_len  max_len
-     FASTA   DNA         58  1,640,848      117  28,290.5  392,611
I checked the version and it showed like this
any2fasta -v                     
any2fasta 0.4.2
abricate --version
abricate 0.5
I don't know whether this happen from the old version?

**Comment by buihoangphuc412** [comment]
Here is the dependencies checking. 
abricate --check
Checking dependencies are installed:
Found 'blastn' => /data/public/Phuc/miniconda3/bin/blastn
Found 'makeblastdb' => /data/public/Phuc/miniconda3/bin/makeblastdb
Found 'seqret' => /data/public/Phuc/miniconda3/bin/seqret
Found 'gzip' => /usr/bin/gzip
Found 'unzip' => /data/public/Phuc/miniconda3/bin/unzip
OK.

**Comment by tseemann** [comment]
abricate 0.5 ?
that is very old.
please update.
