### ISSUE TITLE
ERROR: can not find sequence data 

### ISSUE THREAD

**Issue by TianleiQiu** [tseemann/abricate#148]
Hi， Torsten
When I used the abricate with a my own database, meet the ERROR: "ERROR: can not find sequence data in './assembly/split_contigs/mg.u500.cdhit.contigs.part-06.fa'". The new database had 12085 protein sequences, which was already changed to the style of abricate. My another contigs data (fasta) was successfully filtered with the new database (Found 27606 genes). 
The debug mode was also used, the logs shown this error such as following.
############################################################
........
$VAR1 = {
          'qstart' => '35',
          'sstrand' => 'N/A',
          'qend' => '394',
          'sstart' => '116',
          'slen' => 648,
          'send' => '234',
          'evalue' => '4.90e-22',
          'pident' => '42.500',
          'gapopen' => '1',
          'sseqid' => 'SARG~~~446110287~~~WP_000188142.1~~~',
          'gaps' => 1,
          'qlen' => '843',
          'length' => 120,
          'qseqid' => 'C11k141_79659',
          'stitle' => 'SARG~~~446110287~~~WP_000188142.1~~~ macrolide ABC transporter permease/ATP-binding protein MacB [Escherichia coli] '
        };

$VAR1 = {
          'length' => 390,
          'qseqid' => 'C11k141_79677',
          'stitle' => 'SARG~~~YP_002850162~~~YP_002850162~~~ bicyclomycin/multidrug efflux system [Citrobacter sp. 30_2].',
          'sseqid' => 'SARG~~~YP_002850162~~~YP_002850162~~~',
          'gaps' => 5,
          'qlen' => '7795',
          'evalue' => '2.76e-43',
          'gapopen' => '3',
          'pident' => '31.538',
          'qstart' => '3566',
          'sstrand' => 'N/A',
          'qend' => '4726',
          'sstart' => '3',
          'slen' => 396,
          'send' => '390'
        };

ERROR: can not find sequence data in './assembly/split_contigs/mg.u500.cdhit.contigs.part-06.fa'
#############################################################################
This contigs(mg.u500.cdhit.contigs.part-06.fa) have been successufully filtered with the CARD databases. I am confused with this error. Thanks so much for your help!

The scripts, log files and database were pasted.
Scripts: [ABRicate_contigs_SARG_test_part06.txt](https://github.com/tseemann/abricate/files/4707156/ABRicate_contigs_SARG_test_part06.txt)
Logs :[slurm-127870.out.txt](https://github.com/tseemann/abricate/files/4707163/slurm-127870.out.txt)
Database [SARG.db.txt](https://github.com/tseemann/abricate/files/4707165/SARG.db.txt)

**Comment by tseemann** [comment]
Abricate does not work with protein databases.
It is for NUC:NUC comparisons.

**Comment by madeleinevlt** [comment]
Dear Torsten,
I am reopening this issue because I am a bit confused of your answer about DNA:DNA comparisons. As mentionned by https://github.com/tseemann/abricate/issues/113#issuecomment-536254559 you look at the db info type to use blastn or blastx. So if you are using protein database, it should work with blastx.
Or as you mentionned here https://github.com/tseemann/abricate/issues/113#issuecomment-536243352, blastx results doesn't work (segmentation fault, or something else) ? And also, is blastx used for something else in abricate ?

Best regards,
