### ISSUE TITLE
Add genomes with no genes found to results/output

### ISSUE THREAD

**Issue by Leytoncito** [tseemann/abricate#162]
When bitmaping from abricated results, it is especially useful to have genomes with no results (no gene). This could be useful when adding other analysis independent of the abricate, including presence / absence of specific genes, presence of phages, plasmids, mobile elements and a myriad of characteristics. The contrast that can be generated between genomes / sequences without genes and with genes when these analyzes are included can be potentially important. Now for small analyzes, I have addressed this problem manually, however for analyzes that cover hundreds of genomes it is more complicated.
If you can add this, my heart will be very grateful to you.

**Comment by Leytoncito** [comment]
Bueno una solución sería agregar un gen de referencia or blank gen. Obviously we have to know before which gene is present in all sequences. 
Obviously we have to know first which genes are present in all sequences, perhaps it is even a good practice.

**Comment by andersgs** [comment]
Have you tried `--summary`?

https://github.com/tseemann/abricate/#combining-reports-across-samples

**Comment by Leytoncito** [comment]
yes, i have tried. But its the same. This concatenates only the genomes on which it hit.
