### ISSUE TITLE
Can not find sequence data in 'file'

### ISSUE THREAD

**Issue by d-yarmosh** [tseemann/abricate#17]
Forgive me if this is a known or simple issue. I have all of the necessary perl modules and Abricate, itself, installed. I am trying to feed it a fasta file with ~6000 sequences in it. This fasta was converted from fastq format. I am receiving an error message saying "WARNING: can not find sequence data in 'file_name'

I have tried using EMBOSS' seqret program to reformat the file again. It's definitely a slightly different format, but the error persists. 

It clearly has sequence data at roughly 150 bp per read and the standard Identifier line beginning with ">"

Any thoughts on this?

Thanks

**Comment by kwongj** [comment]
1. Have you tried testing on a FASTA file of assembled contigs or a closed reference genome from Genbank?
2. If you don't have a file to test on, you could try:
```abricate [path_to_abricate_dir]/db/resfinder/sequences```
3. Could you post the first 20 lines of your FASTA file here to help with troubleshooting?

**Comment by tseemann** [comment]
What does `seqret -h` say?
```
Read and write (return) sequences
Version: EMBOSS:6.6.0.0
```
And `abricate --version` ?
```
abricate 0.5
```

**Comment by d-yarmosh** [comment]
seqret -h shows exactly what you wrote - EMBOSS:6.6.0.0

abricate is 0.6-dev version. Should I step down to the previous version?

**Comment by d-yarmosh** [comment]
A FASTA pulled from Genbank and reformatted with seqret works just fine.


The first 20 lines of the fasta look like

>1898 1:N:0:4
ATCATAATGTATGTGTGGAACGCTTGCCCTTTTCCAATAAAAAAGAACGCAATTGCAATA
ACAAGCTGACCTACTAATTTTTGTTTTGATGTCAAACCAAGATTTCTCTTCTTAACTACC
TTTATGTAGTCATCTAAAAACCCAATCAAT
>1979 1:N:0:4
CGTTTTACACGTGTCGCAAGTACAGGATGTCCTTCTGTTGGATTCGCACCAACGATAATG
ACAAGACCTGCTTCAGCTATATCTTTCACTGTTCCAGCATCGCCGCCCATACCGACAGTT
TTAAATAGACCATCTGTTGCTGGAGATTGG
>2326 1:N:0:4
ACATATGTCTTGCGACAATCAAGTCGTAGTAATTAGCTTCAAAAGGAAGTTTTCCAGCGT
CACCTAGTCTCCATTCAATTAAATTATTCGTTTTAGTGGCTTCAGAAAGCATGGCTTCTG
ATTGATCAAAACCGGTTAATTGACCTTTATG
>2401 1:N:0:4
GTATTATTAGCTCAAAATGAGTTACGACAATATTTACAAATTGAGCCTGAAAAACAAATA
AATATGGTTATTTCACTCGGTTTTCCGAAGGATAAACCGAAGAAACTTCCAAGAAAAGAA
GTAGATGAGATTACAACGTTTGTTTTTTAAA
>2496 1:N:0:4
CCACATATCACCATGCTTCCACCTCGAACCTATCAACCTGATCATCTTTCAGGGATCTTA
CTAGCTTACGCTATGGGAAATCTCATCTTGAGGGGGGCTTCATGCTTAGATGCTTTCAGC
ACTTATCCCTTCCGCACATAGCTACCCAG

Do you see anything anomalous here? I have also tried this same file with
only the first field in the line headers.

Thanks,
Dave

**Comment by tseemann** [comment]
@d-yarmosh Dave, that file doesn't look too bad.   It may not be the FASTA file...

I run a single command:
```
gzip -d -c -f YOURFILE | seqret -auto -filter -osformat2 fasta | blastn
```
If that returns a line without the correct number of TSV columns, I print the above error. So it could be any of the steps. 

What version of blastn do you have?   You need at least 2.2.27 I think.
```
% blastn -version

blastn: 2.6.0+
 Package: blast 2.6.0, build May 11 2017 17:54:19
```

**Comment by d-yarmosh** [comment]
I am running blastn 2.6.0, as well.

I have attached my fasta file. I attempted to blast it directly, but got no hits to the vfdb and an error saying some of the query sequences could not calculate ungapped K-A parameters due to invalid query sequence or translation.
[PAN-141-10.seqret.fasta.gz](https://github.com/tseemann/abricate/files/1152829/PAN-141-10.seqret.fasta.gz)

**Comment by kwongj** [comment]
Hi Dave,

There are a couple of sequences that only have Ns:
```
$ grep -v ">" PAN-141-10.seqret.fasta | grep -v [ACGT]
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
```
Removing those sequences from your FASTA file should work with `abricate`. I think it is a `blastn` requirement that all characters are nucleotides (i.e. `A`, `C`, `G`, or `T`).

**Comment by tseemann** [comment]
I guess I need to filter out "bad" sequences.

**Comment by tseemann** [comment]
THis filtering would take too much new code and would slow abricate down dramatically.

I consider it a bug in the contig generating software to have a contig with only N letters.

**Comment by barrantesisrael** [comment]
FYI: The same error is triggered when the fasta contains an empty sequence. Running this `awk` command fixes the problem:

`awk 'BEGIN {RS = ">" ; FS = "\n" ; ORS = ""} {if ($2) print ">"$0}' input.fasta > output.fasta`
