### ISSUE TITLE
Can't update databases

### ISSUE THREAD

**Issue by nataliagaeta29** [tseemann/abricate#172]
Hello everyone

I am using abricate 0.8 (UBUNTU 20.04 LTS). When I use abricate-get_db --force -db ncbi (or other databases), I get this:

Can't locate Bio/Seq.pm in @INC (you may need to install the Bio::Seq module) (@INC contains: /home/gaeta/miniconda3/envs/bioinfo/lib/site_perl/5.26.2/x86_64-linux-thread-multi /home/gaeta/miniconda3/envs/bioinfo/lib/site_perl/5.26.2 /home/gaeta/miniconda3/envs/bioinfo/lib/5.26.2/x86_64-linux-thread-multi /home/gaeta/miniconda3/envs/bioinfo/lib/5.26.2 .) at /home/gaeta/miniconda3/envs/bioinfo/bin/abricate-get_db line 3. BEGIN failed--compilation aborted at /home/gaeta/miniconda3/envs/bioinfo/bin/abricate-get_db line 3.

How can I solve it?

Thanks in advance!

Naty

**Comment by andersgs** [comment]
@nataliagaeta29 you need to update your Bio Perl to a later version. 

```
conda install -c conda-forge -c bioconda perl-bioperl=1.7.2
```

**Comment by nataliagaeta29** [comment]
Hello andersgs

thanks for your answer. I tried your code and I got this:

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package zlib conflicts for:
perl-bioperl=1.7.2 -> perl-bio-samtools -> zlib[version='>=1.2.11,<1.3.0a0']
python=3.8 -> zlib[version='>=1.2.11,<1.3.0a0']

Package libgcc-ng conflicts for:
python=3.8 -> zlib[version='>=1.2.11,<1.3.0a0'] -> libgcc-ng[version='>=4.9|>=7.2.0']
python=3.8 -> libgcc-ng[version='>=7.3.0|>=7.5.0|>=9.3.0']The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.31=0
  - python=3.8 -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
Your installed version is: 2.31

I am new in this programming field. 
Could you help me to understand which package(s) I should update?

Thanks!

Naty

**Comment by andersgs** [comment]
Are you tied down to abricate v0.8? Can you upgrade to abricate 1.0.1?

Unfortunately, conda can behave oddly when trying to figure out all the dependencies that might work together. That is not a conda isolate issue. Dependency hell is true in most places. :)

```
conda install -c conda-forge -c bioconda abricate=1.0.1
```

If not, start a new conda environment:

```
conda create -n abricate abricate=1.0.1
```

**Comment by nataliagaeta29** [comment]
Hi @andersgs 

I started a new conda environment and it worked!

Thank you so much!

Naty
