### ISSUE TITLE
something wrong with mcr-1.6_1

### ISSUE THREAD

**Issue by a1204350** [tseemann/abricate#18]
123.fasta | NODE_126_length_2763_cov_117.927 | 775 | 2600 | mcr-1.6_1 | 1-1826/1826 | Err:510 | 0/0 | 100 | 99.89
-- | -- | -- | -- | -- | -- | -- | -- | -- | --

according to KY352406, the length of mcr-1.6_1 should be 1626 bps, the same as the other mcr-1 variants. However, as you can see at the top, it shows 1826 bps.

I also double-checked it with the online version of resfinder, it gave a correct match with mcr-1 (1626), so I'm wondering where it went wrong.

Thanks so much

**Comment by tseemann** [comment]
This is the sequence that is in Resfinder latest version:
It says 1826 bp. Please contact the Resfinder team if this is wrong.
See Valeria's contact details at https://cge.cbs.dtu.dk/services/ResFinder/

You have an unexpected 'Err:510' in your COVERAGE_MAP column.
I also notice you are using an old verison of Abricate, can you upgrade to 0.5 ?


```
>resfinder~~~mcr-1.6_1~~~KY352406 mcr-1.6_1
CGCATAATTTTTTATATCAGATAAATTGTACTGGATTTCTTAAAAAATTGCAGTATAATT
GCCGCAATTATCCCACCGTTTATTTTTTTAATAGTTTCTCATGATGCAGCATACTTCTGT
GTGGTACCGACGCTCGGTCAGTCCGTTTGTTCTTGTGGCGAGTGTTGCCGTTTTCTTGAC
CGCGACCGCCAATCTTACCTTTTTTGATAAAATCAGCCAAACCTATCCCATCGCGGACAA
TCTCGGCTTTGTGCTGACGATCGCTGTCGTGCTCTTTGGCGCGATGCTACTGATCACCAC
GCTGTTATCATCGTATCGCTATGTGCTAAAGCCTGTGTTGATTTTGCTATTAATCATGGG
CGCGGTGACCAGTTATTTTACTGACACTTATGGCACGGTCTATGATACGACCATGCTCCA
AAATGCCCTACAGACCGACCAAGCCGAGACCAAGGATCTATTAAACGCAGCGTTTATCAT
GCGTATCATTGGTTTGGGTGTGCTACCAAGTTTGCTTGTGGCTTTTGTTAAGGTGGATTA
TCCGACTTGGGGCAAGGGTTTGATGCGCCGATTGGGCTTGATCGTGGCAAGTCTTGCGCT
GATTTTACTGCCTGTGGTGGCGTTCAGCAGTCATTATGCCAGTTTCTTTCGCGTGCATAA
GCCGCTGCGTAGCTATGTCAATCCGATCATGCCAATCTACTCGGTGGGTAAGCTTGCCAG
TATTGAGTATAAAAAAGCCAGTGCGCCAAAAGATACCATTTATCACGCCAAAGACGCGGT
ACAAGCAACCAAGCCTGATATGCGTAAGCCACGCCTAGTGGTGTTCGTCGTCGGTGAGAC
GGCACGCGCCGATCATGTCAGCTTCAATGGCTATGAGCGCGATACTTTCCCACAGCTTGC
CAAGATCGATGGCGTGACCAATTTTAGCAATGTCACATCGTGCGGCACATCGACGGCGTA
TTCTGTGCCGTGTATGTTCAGCTATCTGGGCGCGGATGAGTATGATGTCGATACCGCCAA
ATACCAAGAAAATGTGCTGGATACGCTGGATCGCTTGGGCGTAAGTATCTTGTGGCGTGA
TAATAATTCGGACTCAAAAGGCGTGATGGATAAGCTGCCAAAAGCGCAATTTGCCGATTA
TAAATCCGCGACCAACAACGCCATCTGCAACACCAATCCTTATAACGAATGCCGCGATGT
CGGTATGCTCGTTGGCTTAGATGACTTTGTCGCTGCCAATAACGGCAAAGATATGCTGAT
CATGCTGCACCAAATGGGCAATCACGGGCCTGCGTATTTTAAGCGATATGATGAAAAGTT
TGCCAAATTCACGCCAGTGTGTGAAGGTAATGAGCTTGCCAAATGCGAACATCAGTCCTT
GATCAATGCTTATGACAATGCCTTGCTTGCCACCGATGATTTCATCGCTCAAAGTATCCA
GTGGCTGCAGACGCACAGCAATGCCTATGATGTCTCAATGCTGTATGTCAGCGATCATGG
CGAAAGTCTGGGTGAGAACGGTGTCTATCTACATGGTATGCCAAATGCCTTTGCACCAAA
AGAACAGCGCAGTGTGCCTGCATTTTTCTGGACGGATAAGCAAACTGGCATCACGCCAAT
GGCAACCGATACCGTCCTGACCCATGACGCGATCACGCCGACATTATTAAAGCTGTTTGA
TGTCACCGCGGACAAAGTCAAAGACCACACCGCATTCATCCGCTGATTTCTCCCTGTATT
TTTTCCAAACCCACCGCACACTCCATTCGTATTATGGGCGGTGGGGTGGGGTTTGTTATG
CCGTATTTATCAAATAAACGCCTACT
```

**Comment by tseemann** [comment]
You are right, it does look suspicious!

```
resfinder~~~mcr-1.2_1~~~KX236309        dna     1626
resfinder~~~mcr-1.3_1~~~KU934208        dna     1626
resfinder~~~mcr-1.4_1~~~KY041856        dna     1626
resfinder~~~mcr-1.5_1~~~KY283125        dna     1626
resfinder~~~mcr-1.6_1~~~KY352406        dna     1826
resfinder~~~mcr-1.7_1~~~KY488488        dna     1626
resfinder~~~mcr-1.9_1~~~KY685071        dna     1626
resfinder~~~mcr-1_1~~~KP347127  dna     1626
```

**Comment by a1204350** [comment]
thanks for the quick reply!
I checked the version just now, and showed 0.5
I've got Err:510 since the beginning. I'm not sure why that happened, anyway I don't think it will affect the result.
cheers

**Comment by tseemann** [comment]
@a1204350  we confirm that mcr-1.6 has 100bp up and downstream added.

I have contacted Valeria the curator.

I really appreciate the report!

**Comment by tseemann** [comment]
@a1204350 they have fixed the database 
https://bitbucket.org/genomicepidemiology/resfinder_db/commits/all
I will make a new release of Abricate this week.

**Comment by a1204350** [comment]
really appreciate!!

**Comment by tseemann** [comment]
@a1204350 actually you can run `abricate-get_db --db resfinder --force` yourself!
