### ISSUE TITLE
dependency hdf5 is not available

### ISSUE THREAD

**Issue by maculatus** [tseemann/abricate#19]
Hello Torsten,
brew seems not to have hdf5 available. I installed via ubuntu but still not recognized by abricate. Perhaps, the dependecies need to be changed and the place where to find hdf5?

brew install abricate
Updating Homebrew...
==> Installing abricate from tseemann/bioinformatics-linux
Error: No available formula with the name "hdf5" (dependency of tseemann/bioinformatics-linux/abricate)
It was migrated from homebrew/science to homebrew/core.

**Comment by ggarofolo** [comment]
hello Torsten,
I have the same problem and Error:
Error: No available formula with the name "hdf5" (dependency of tseemann/bioinformatics-linux/abricate)
It was migrated from homebrew/science to homebrew/core.
Perhaps the dependency has a different name hdf5@1.8

**Comment by tseemann** [comment]
Yes, you are correct about the brew migration.   I think Linuxbrew is now matched up with main brew. Please try `brew update ; brew upgrade ; brew doctor` to see if that fixes it.

**Comment by maculatus** [comment]
hello, I installed nanopolish and this fix the problem installing hdf5
automatically.

**Comment by tseemann** [comment]
@maculatus the HDF5 issue was solved yesterday by the Homebrew teams.  nanopolish would not have installed before that either.

**Comment by maculatus** [comment]
Thanks!
