### ISSUE TITLE
error updating MEGARES

### ISSUE THREAD

**Issue by stalact** [tseemann/abricate#198]
I have some issues with updating the MEGARES database: 

 abricate-get_db --db megares --force
Setting up 'megares' in '/abricate-1.0.1/db/megares'
Downloading: https://megares.meglab.org/download/megares_v2.00.zip
HTTP Result: 200
Destination: megares.zip
Filesize: 55162 bytes
Archive:  megares.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of megares.zip or
        megares.zip.zip, and cannot find megares.zip.ZIP, period.
load_fasta:

------------- EXCEPTION: Bio::Root::Exception -------------
MSG: file argument provided, but with an undefined value
STACK: Error::throw
STACK: Bio::Root::Root::throw /usr/share/perl5/Bio/Root/Root.pm:449
STACK: Bio::SeqIO::new /usr/share/perl5/Bio/SeqIO.pm:394
STACK: main::load_fasta /abricate-1.0.1/bin/abricate-get_db:727
STACK: main::get_megares /abricate-1.0.1/bin/abricate-get_db:352
STACK: /abricate-1.0.1/bin/abricate-get_db:60
-----------------------------------------------------------

is there a proper way for getting the updated database?

**Comment by pratyaysengupta** [comment]
Also facing the same! With all the databases :(

**Comment by aastha-batta** [comment]
Hi, The link used to update database is old. Kindly go to line 350 in bin/abricate-get_db and do `download('https://www.meglab.org/downloads/megares_v3.00.zip', $zip);` This might help.

**Comment by pratyaysengupta** [comment]
> Hi, The link used to update database is old. Kindly go to line 350 in bin/abricate-get_db and do `download('https://www.meglab.org/downloads/megares_v3.00.zip', $zip);` This might help.

Many Thanks

**Comment by stalact** [comment]
Thanks for your help! :-)
