### ISSUE TITLE
Need to install JSON module on Ubuntu for updating databases

### ISSUE THREAD

**Issue by dutchscientist** [tseemann/abricate#20]
On Ubuntu 14.04 LTS2 (Biolinux8) and Ubuntu 16.04 I have had to manually install JSON with CPANM to be able to use the "abricate-get_db --db resfinder --force".

Maybe add this to the readme?

"sudo cpanm install JSON".

**Comment by tseemann** [comment]
You are right, this new dependency was not documented.

You can install most Perl dependencies more nicely by using apt-get. I think `apt-get install libjson-perl` should work.
