### ISSUE TITLE
Fails on Biolinux8 due to BLAST+ version?

### ISSUE THREAD

**Issue by dutchscientist** [tseemann/abricate#21]
Biolinux8 is Ubuntu 14.04 LTS, and this one has BLAST+ v 2.2.28 as final one in its repositories. Hence Abricate won't run (it expects >= 2.2.30), and the check does not pick this up.

How easiest to correct?

**Comment by dutchscientist** [comment]
Have done it the blunt way by just downloading the executables from ftp://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/2.6.0/ncbi-blast-2.6.0+-x64-linux.tar.gz and copying all them to /usr/bin. Not pretty but Abricate works then.

Worth mentioning in the readme? There may be more people still using Biolinux8.

Do you know whether a higher version of BLAST+ can be forced to install on 14.04? I couldn't find an apt-get line for it. On 16.04 it is not a problem.

**Comment by tseemann** [comment]
Ideally --check would check the version, but it's too much effort.  Ubuntu 14 is >3 years old, and 2.2.28 blast is old now.

You need to figure out how to add new /apt/sources with new builds of BLAST+ for 14.04, or build the packages from debian source packages maybe. 

Or just install Linuxbrew.
