### ISSUE TITLE
Add option to define minimum coverage?

### ISSUE THREAD

**Issue by dutchscientist** [tseemann/abricate#22]
Currently Abricate will also report partial hits. An option to define the minimum coverage required (similar to --minid=95 or so) would be a good option. So say --mincov=90 or so?

**Comment by tseemann** [comment]
This could be done with post-filtering of the output TSV file but it is easy to add to I have added it as `--mincov` with default 0 as to be backward compatible. But remember, the identity is still measured relative to the partial hit, not the whole match.

**Comment by dutchscientist** [comment]
Excellent. I am trying to implement it for things like rapid phylogrouping for E. coli, and with mincov I can have more discriminatory options. I have shown ABRicate to several people now to an enthusiastic response!
