### ISSUE TITLE
Remove ! from option in --help output

### ISSUE THREAD

**Issue by dutchscientist** [tseemann/abricate#23]
If you do abricate --help. the output contains exclamation marks after debug, quiet, version etc. These should not be included.

When I was explaining this to students, they thought it was confusing. Why add the exclamation mark when it should not be used?

**Comment by tseemann** [comment]
These are symbols used in Perl `getopt`  for different option types. 
`!` means boolean, `=s` means string etc.
But yes it is confusing to regular people. 
I will fix it.

**Comment by tseemann** [comment]
Fixed in HEAD.

**Comment by dutchscientist** [comment]
Thanks :)
