### ISSUE TITLE
ERROR: abricate --list 

### ISSUE THREAD

**Issue by mmaesaar** [tseemann/abricate#24]
abricate --list gives 

abricate: corrupt database? - /usr/local/Cellar/abricate/0.5/bin/../db/abricate

how to resolve it?

Thanks

**Comment by tseemann** [comment]
This bug does not affect anything, but I have fixed it in 944b4366e7f7f24c3abd602b8b7cc96c884711fa but I have not made a new release yet.

You can run `rm -fr /path/to/abricate/db/abricate` to get rid of it now if you want.
