### ISSUE TITLE
Automate finding latest CARD version

### ISSUE THREAD

**Issue by tseemann** [tseemann/abricate#25]
`https://card.mcmaster.ca/download/0/broadstreet-v1.1.9.tar.gz`

**Comment by dswan** [comment]
FWIW there is a 'latest' endpoint for CARD:

`wget https://card.mcmaster.ca/latest/data -O cardLatest.bz2`

**Comment by tseemann** [comment]
@dswan - Thank Dan!  And it even has the correct `.bz2` extension! But no .tar?

**Comment by dswan** [comment]
@tseemann actually I'm sure it is a tarball wrapped up underneath that. So -O cardLatest.tar.bz2 might have been a better suggestion on my part!

I also note that ARIBA handles this quite neatly to expose multiple versions.

**Comment by tseemann** [comment]
I have switched - thanks for the tip Dan!  @dswan
