### ISSUE TITLE
no ncbi database?

### ISSUE THREAD

**Issue by r0sies** [tseemann/abricate#27]
Hi Torsten, Jason, just checking.. is the ncbi database no longer used in abricate 0.5? Thanks, Rosie

**Comment by tseemann** [comment]
I have not removed any databases. The only one in 0.5 was `ncbibetalactamases`. I added a new `ncbi` one in 0.6 too. 

You should upgrade to 0.6 and follow the new installation instructions ie. run `abricate --setupdb`.
