### ISSUE TITLE
feature request: send description from database headers to output table

### ISSUE THREAD

**Issue by schultzm** [tseemann/abricate#33]
Hi @tseemann , 

Feature request: add a new column to the abricate output that contains 'DESCRIPTION' information.   For example, the `ncbi` database has 
```
>ncbi~~~mcr-1~~~A7J11_03461 phosphoethanolamine--lipid A transferase MCR-1
>ncbi~~~mcr-1.2~~~A7J11_03754 phosphoethanolamine--lipid A transferase MCR-1.2
>ncbi~~~mcr-1.3~~~A7J11_04944 phosphoethanolamine--lipid A transferase MCR-1.3
``` 
in the headers.  I would like to be able to extract from the abricate stdout that mcr-1.3 is a `phosphoethanolamine--lipid A transferase`

Thanks

**Comment by tseemann** [comment]
Ok, there is a now a `PRODUCT` column.  
Only some DBs and some genes have a product though.

**Comment by schultzm** [comment]
lightning-fast update.  thanks!

**Comment by nalbright** [comment]
Where in the fasta header does the product information need to be. I have tried running a database with headers having a space and description (as per instructions for custom DB), but it does not display "product" in the output .csv. Is there a flag that I am missing? or do I have that information in the wrong spot in the fasta header? 
Thanks! 
Nicolette

**Comment by tseemann** [comment]
@nalbright can you paste the first line of your database `sequences` file? 
and also what does `abricate --version` say?

**Comment by nalbright** [comment]
I am running abricate through biocontainer --version: abricate 0.5-dev

Header: 
>S_epidermidis_ISOLATEDB~~~NP_763556.1~~~OINGLKLB_00795 chromosome replication initiator DnaA; 1056816

Thanks!

**Comment by tseemann** [comment]
@nalbright your version of Abricate is too old. Support for `PRODUCT` came after 0.5.
