### ISSUE TITLE
Interested in additional databases?

### ISSUE THREAD

**Issue by dutchscientist** [tseemann/abricate#38]
I have converted the SerotypeFinder and EcOH (SRST2) databases for E. coli serotyping to Abricate format. Are you interested in such databases to be made generally available? I am happy to share.

**Comment by tseemann** [comment]
I can't just 'include' databases. They need to be able to be automatically downloaded and built using the `abricate-get_db --db XXX` command.  I have done the EcOH one before, but to truly parse the results you need some domain knowledge about the weird combinations that can occur.

**Comment by dutchscientist** [comment]
OK, great :)
