### ISSUE TITLE
Format for database

### ISSUE THREAD

**Issue by karinlag** [tseemann/abricate#4]
Hi!

I'd love to use this for other genes. Could you specify what the fasta description line should look like, for instance, which part(s) of it do you use where?

**Comment by tseemann** [comment]
I strip the part of the ID after underscore.

I've added it to the docs: https://github.com/tseemann/abricate#adding-your-own-sequences

This behavious may change soon as I add drug-class to the BLAST DB and stop including all the .fsa files.
