### ISSUE TITLE
Add database: SerotypeFinder

### ISSUE THREAD

**Issue by tseemann** [tseemann/abricate#40]
Issue #38 by @dutchscientist
https://cge.cbs.dtu.dk/services/SerotypeFinder/

@dutchscientist do you have the URL for the amplicon sequences?

**Comment by dutchscientist** [comment]
"@dutchscientist do you have the URL for the amplicon sequences?"

Which amplicon sequences?

**Comment by tseemann** [comment]
@dutchscientist for Serotype finder?   The website has no database to download?

**Comment by dutchscientist** [comment]
Ah. I did manage to download it, just need to find the link back. I can upload the database I made for it?

**Comment by tseemann** [comment]
@dutchscientist no you can't just give it to me, i need a URL or systematic way to download it etc.  

I think this must be it:
https://bitbucket.org/genomicepidemiology/serotypefinder_db/src

**Comment by tseemann** [comment]
Actually, i already have the SRST2 cleaned version of this database as `--db ecoh`.
Is that what you want?
ie. `fliC` and `wxz`etc?

**Comment by dutchscientist** [comment]
Yes, that's the link! Well done, I found it before and forgot to bookmark it...

The EcOH and serotypefinder databases are very similar, but not identical. Am not enough of an E. coli expert to have a preference, some people may prefer the one, some the other?

**Comment by tseemann** [comment]
I think these are the same thing, and the SRST2 one is more up to date,

**Comment by andersgs** [comment]
I would trust the SRST2 one. It has been curated by Danielle Ingle. That is what we use at MDU.
