### ISSUE TITLE
CARD database is outdated

### ISSUE THREAD

**Issue by phiweger** [tseemann/abricate#41]
I am trying to use the latest version of CRAD, which is 1.2 via 

```
abricate-get_db --db card --force

Setting up 'card' in '/Users/pi/miniconda3/db/card'
Downloading: https://card.mcmaster.ca/download/0/broadstreet-v1.1.9.tar.gz
Result: 200
Destination: card.tar.bz2
```

However, the most recent version is [1.2.0](https://card.mcmaster.ca/download).

I tried changing the `card.tar.bz2` in the `.../miniconda3/db/card/src/` and then reloaded the db with 

```
abricate-get_db --db card
```

no effect, still uses 1.1.9

What am I doing wrong?

**Comment by viehwegerlib** [comment]
Ok, so I edited [abricate-get_db](https://github.com/tseemann/abricate/blob/2d3bdf5261cc2ebcd767207234123994075a97bd/bin/abricate-get_db) and changed the version to `1.2.0`. iI there a way to not have the database version hard-coded?

**Comment by tseemann** [comment]
@phiweger 
I don't know why the get_db didn't change. Did you you `--force` like it said to?
Maybe you didn't see what it printed:
```
% abricate-get_db --db card
Setting up 'card' in '/home/tseemann/git/abricate/db/card'
Won't re-download existing card.tar.bz2 (use --force)
```

As for the version, you should email the CARD people to make it easy to get the latest one. They need to provided a `card-latest.tgz` file or similar.
I have an issue on this already: https://github.com/tseemann/abricate/issues/25

The database is updated in git now.
