### ISSUE TITLE
Card Summary Header

### ISSUE THREAD

**Issue by logan-fink** [tseemann/abricate#42]
There seems to be a small issue with the formatting of the last columns in the card_summary output file header, I believe they are supposed to read smeR, and then sul1, but for me, they appear concatenated, with no tab in between. Extremely minor issue, but I thought I'd let you know!  

Thank you, I really appreciate the software!

**Comment by tseemann** [comment]
@logan-fink i'm not sure what you mean?  can you give me an example of what you ran? do you mean the `--summary` output? or regular `abricate` output?   it could be bugs in the CARD database itself, i only copy what's in the JSON file.
