### ISSUE TITLE
abricate-get_db feature requests

### ISSUE THREAD

**Issue by schultzm** [tseemann/abricate#44]
Hi Torsten, 
Feature requests:

- add `--help` to `abricate-get_db`
- allow user to specify db url or path to db if already downloaded (e.g., `http://www.mgc.ac.cn/VFs/Down/VFDB_setB_nt.fas.gz` instead of `http://www.mgc.ac.cn/VFs/Down/VFDB_setA_nt.fas.gz` )
- during the running of `abricate-get_db`, append unique identifier to locus tag so duplicate error does not occur (`BLAST Database creation error: Error: Duplicate seq_ids are found:`)

Cheers, 

Mark

**Comment by tseemann** [comment]
1.  that was already done at some point

2. lots of post-processing needs to be done to most FASTA files to get them into the Abricate format, so I'm not sure how that could work?    Also, often other metadata tables are joined.

3. Those should be reported to upstream database maintainers?
