### ISSUE TITLE
downloading CARD using abricate-get_db - card format changed

### ISSUE THREAD

**Issue by EpiBlake** [tseemann/abricate#47]
Hi Torsten, 

I was trying to update the CARD database to the most updated version using the abricate-get_db command but the command failed with the following error:

```
Downloading: https://card.mcmaster.ca/download/0/broadstreet-v1.1.9.tar.gz
Result: 501
Destination: card.tar.bz2
Filesize:  bytes
tar: card.tar.bz2: Cannot open: No such file or directory
```

Looks like the CARD database finally made the switch to tar.gz. Can you update the get_db script to change the .bz2 to .gz? 

Thanks!

**Comment by EpiBlake** [comment]
One other note, this goes with the new v2.0.0 that just came out.

**Comment by tseemann** [comment]
@EpiBlake I just updated my git yesterday for 2.0.0 CARD. I haven't made a release yet though, still updating NCBI and Resfinder too. There will be a new release planned within the next 6 hours!

**Comment by EpiBlake** [comment]
Great, thanks!

**Comment by EpiBlake** [comment]
Hi Torsten,

Just checking to see if you have an update on the new release of abricate you mentioned?

Thanks!

**Comment by tseemann** [comment]
I'm making a release today.
