### ISSUE TITLE
Add licenses for the databases I include

### ISSUE THREAD

**Issue by tseemann** [tseemann/abricate#48]
Need to check I ain't breaking any rules :-/

**Comment by arpcard** [comment]
Thanks @tseemann! See https://github.com/bioconda/bioconda-recipes/pull/7507 for CARD. We added this to the CARD disclaimer to better support Conda:

'The only exception is distribution of the Resistance Gene Identifier software on the Conda open source, cross-platform, language-agnostic package manager and environment management system (https://conda.io/). Conda users are still required to abide by the Terms of Use listed, specifically sections 4 and 5 below.'

However, you are including CARD data, so perhaps we need to expand this? CARD does have restrictions for use by Commercial or Non-Academic Organizations, see https://card.mcmaster.ca/about. If you add text to abricate that points this out and points folks to the CARD website, that would work too.

**Comment by tseemann** [comment]
@arpcard Thanks for your understanding - I will look into this more.  Printing this information at the end of every run, and in the brew installation `caveats` section would also be desirable.

**Comment by tseemann** [comment]
@arpcard I'm not sure you can fully restrict the CARD **sequences** ?  Did you derive them all from scratch? My guess would be your primed it with Resfinder and ARG-Annot (I thought I found identical mistakes in CARD and those?). You did a lot of work on the Ontologies, but I don't use those.

**Comment by arpcard** [comment]
Apologies for dropping this thread @tseemann. Our IP office states “Databases, as CARD represents, are considered “compilations” under Canadian copyright law and the Canadian Copyright Act grants copyright protection to the compiler.  This means that a work resulting from the selection or arrangement of data would receive protection and the data collected in the database need not be original or creative".  I take that to mean CARD itself is copyrighted but your use in abricate is fine.
