### ISSUE TITLE
use multi-threaded blast

### ISSUE THREAD

**Issue by tolot27** [tseemann/abricate#49]
Currently, the blast search against the databases/query is only single-threaded. Blastn supports multi-threaded search natively. It would be great to expose `-num_threads` as an argument to abricate. Otherwise, search in metagenomic assemblies would take ages.

**Comment by tseemann** [comment]
You're right - I thought I had done that, but I haven't (I did it for `mlst`).

I'll add it.

**Comment by tseemann** [comment]
@tolot27 if you use the `git clone` method, there is now a `--threads` option.  I'll make a new release in a few weeks.
