### ISSUE TITLE
can't update database

### ISSUE THREAD

**Issue by a1204350** [tseemann/abricate#51]
Hi there,

I tried to update the database with command "abricate-get_db --force --db ncbi", however it failed throwing out 501 https error.
I then installed LWP::Protocol::https via "cpanm LWP::Protocol::https" and turned out the same error message persisted. After that I also tried "sudo cpanm LWP::Protocol::https" which installed it with the other perl location I suppose, but still not working.
Both ways successfully installed  LWP::Protocol::https, but still did not resolve the problem.
I'm a bit new to all of these, can someone show me how to resolve it, thanks much!

Yu

**Comment by tseemann** [comment]
I also had this issue a year or so ago.  It's related to Perl and OpenSSL.

Are you Linux or MacOS?
Conda, Brew or Git installation?

(I would recommend using Conda or Brew to install all your bioinformatics software)

**Comment by a1204350** [comment]
Thanks for the reply.
It was installed using brew on Ubuntu 16.04 LTS.

**Comment by tseemann** [comment]
Brew has gone through a big change recently, and I've moved and updated the abricate package.

Assuming `brew doctor` is happy, try this:

```
brew untap homebrew/science
brew tap brewsci/bio
brew update
brew reinstall abricate
```

**Comment by a1204350** [comment]
I'll give a try, thanks

**Comment by tseemann** [comment]
I assume it worked.
