### ISSUE TITLE
Summary Table Presence Abscence

### ISSUE THREAD

**Issue by nearinj** [tseemann/abricate#52]
I've looked around the read me, but can't seem to find the answer to this question. In the summary table that is created by combining results across samples there are values between 0-100 in the gene column. With some having multiple values i.e " 48.13;30.89 ". What do these numbers correspond to?

**Comment by tseemann** [comment]
That is the % coverage of the gene that was found in the genome.

Ideally it would be "100.00".

But if the gene was fragmented due to poor assembly, then it will show you all the parts it found.

"48.13,30.89" means it found 48% in one place, and 31% in another. not clear where the other 21% went.
