### ISSUE TITLE
database of PlasmidFinder

### ISSUE THREAD

**Issue by zhaoxvwahaha** [tseemann/abricate#53]
If each sequence in PlasmidFinder database represent a different plasmid? I noticed that the name of sequence is same with the name of probe used, but different probes could correspond to same gene (at different region). So, if my one sample annotate more than one sequences in database, that means there are more than one plasmids in this sample?

**Comment by felipelira** [comment]
It is possible if you have more than one plasmid in your organism. Extract the contigs that you got a good hit for PlasmidFinder and make a Blast to check the closest plasmid for each one.

**Comment by tseemann** [comment]
@zhaoxvwahaha I do not know the answer to your question. I just added this database: https://cge.cbs.dtu.dk/services/PlasmidFinder/
