### ISSUE TITLE
Argannot database broken when updated?

### ISSUE THREAD

**Issue by dutchscientist** [tseemann/abricate#56]
I updated the Argannot database with the command:

abricate-get_db --db argannot --force

That leads to a broken database with lots of N's. The source file corrupt or link broken?

**Comment by tseemann** [comment]
What version of abricate were you using?

**Comment by dutchscientist** [comment]
The one installed by conda, so 0.9?

**Comment by dutchscientist** [comment]
Will stick to Resfinder and NCBI then, no worries.  Just wanted to make sure you are aware :)

**Comment by tseemann** [comment]
I would advise to only use NCBI.   Resfinder has too many partial ORFs.

**Comment by dutchscientist** [comment]
OK, thanks. Maybe a good idea to make it the default database in future versions?

**Comment by tseemann** [comment]
I intend to when we've finished out audits of resfinder.   
Don't want to change results suddenly as many people have existing pipelines where it is assumed.
