### ISSUE TITLE
bitscore in CARD output and summary 

### ISSUE THREAD

**Issue by darwinbandoy** [tseemann/abricate#65]
Card-RGI usually generates bitscore to classify perfect and strict hits- can that be included as an output in the file of Abricate? And be included in the summary function as well? Thanks!

**Comment by tseemann** [comment]
Bit score is dependent on what tool/method you use to find matches, and whether you use local or global alignment.  I don't plan to add this feature, especially when RGI already does it?

**Comment by agmcarthur** [comment]
I agree with @tseemann, if you started to add CARD bitscores to abricate, you would also need CARD's model types. Not all bitscores are used the same way by RGI. @tseemann is also correct that bitscore depends highly upon the method. We had a lot of work to do at CARD to make sure RGI using BLAST versus DIAMOND was not biasing results. RGI is very specific about BLAST and DIAMOND version types for this very reason - not sure how translatable CARD bitscore cut-offs will be outside of RGI.

**Comment by darwinbandoy** [comment]
I was not specifically thinking of the technicalities of the bitscore ( I apologize for that and please be patient with my inexperience), but I was using abricate (inputting the CARD database) because abricate can generate a summarized version of all the runs. I am analyzing 113 genomes and merging together them in one file seems a challenge using CARD RGI per se,  so I used abricate summary but my PI needs the strict,perfect hits threshold. So essentially I dingdong between the tools.

**Comment by agmcarthur** [comment]
@darwinbandoy RGI can be downloaded as a command line tool for bulk analyses. Happy to receive suggestions for tools needed for summarizing.

**Comment by darwinbandoy** [comment]
@agmcarthur I downloaded RGI and did the analysis. I emailed you my feature request for summary, thank you very much for your time! I think CARD RGI website is very easy to use- merging multiple files into a single report is the challenge.

**Comment by tseemann** [comment]
One thing to be careful of is that I believe `RGI` depends on `prodigal` to find genes, which are then protein:protein matched (?).   Whereas `abricate` uses the CDS (DNA alleles) to align directly to the contigs.  Both approaches have advantages and disadvantages, so just keep it in mind.
