### ISSUE TITLE
PlasmidFinder data should be downloaded from BitBucket

### ISSUE THREAD

**Issue by VGalata** [tseemann/abricate#66]
Dear Torsten,

I found out that for plasmidFinder the tool uses an old link to download the sequence files. The data is now stored in a [BitBucket repository](https://bitbucket.org/genomicepidemiology/plasmidfinder_db.git). The timestamp of the files downloaded from the old link is from 2017 while the newest sequence files are from 2018.09.04. Thus, the used address should be replaced by `https://bitbucket.org/genomicepidemiology/plasmidfinder_db/get/HEAD.zip`.

Also, as the files have now different names, it is better to make sure to remove the old files before downloading the new data and creating the databases.

**Comment by tseemann** [comment]
@VGalata thanks for letting me know! I should have realised that resfinder is also only up to date on bitbucket so it makes sense that it should be true for their other products.

**Comment by tseemann** [comment]
They seem to have changed their ID syntax a bit too. More regexp munging ahead!
