### ISSUE TITLE
abricate vs resfinder.py

### ISSUE THREAD

**Issue by LeonardosMageiros** [tseemann/abricate#69]
Hi!

I was wondering if abricate (using the default database) should give the same results with resfinder.py provided by the resfinder website as I am trying to compare the two and I am having different results for the same contigs fasta file. 

Is that normal? Is there an explanation for that? 

Best 
Leonardos

**Comment by tessverschuuren** [comment]
Dear reader,

I am running into a similar issue, I observed a difference in ESBL genes in a subset of my dataset. When running abricate on 25-09 and 24-01, and 07-03 via the resfinder website with the same scaffolds as input, a difference is observed in the predicted blaCTX-M-27/102 and blaSHV-1/102/48. All other isolates in my dataset (n=623), have stable ESBL gene prediction. 

25-09-18	abricate resfinder (resfinder version 3.1.0 27-08-18 (3021 nucleotides)	CTX-M-27 (73/73 isolates, all coverage 100%, identity 100%) 	SHV-1 (5/5 isolates, all coverage 100%, identity 99.88%)
24-01-19	abricate resfinder (resfinder version 3.1.0 27-08-18 (3021 nucleotides)	CTX-M-102 (73/73 isolates, all coverage 100%, identity 99.89%)	SHV-102 (5/5 isolates, all coverage 100%, identity 99.88%)
07-03-19 resfinder webserver version 3.1.0 CTX-M-27 (73/73 isolates coverage 100%, identity 100%), SHV-48 (5/5 isolates coverage 100%, identity 99.88%)

Could a difference in abricate versions be an explanation? Any additional insight in the observed differences is very welcome!

Kind regards,
Tess Verschuuren

**Comment by tseemann** [comment]
You should not expect the exact same results.

I use `blastn` and I think `resfinder` uses `blastp`+`prodigal` gene prediction.
