### ISSUE TITLE
Can this tool be used to create an abundance table of absolute counts per gene/sample?

### ISSUE THREAD

**Issue by slvrshot** [tseemann/abricate#75]
I have some paired-end .fastq files that have already been converted to .fasta for a number of samples and I'd like to create an abundance table based on the frequency of hits per gene in the BacMet confirmed database. Is this something that this tool could help me with?

**Comment by tseemann** [comment]
Abricate does not work on raw reads, you need to de novo assemble them into contigs first.

The BacMet database is protein, not nucleotide, and the implementation I have in Abricate is the wrong way around, and searching takes days instead of minutes. So no, not really.

**Comment by slvrshot** [comment]
Sorry I should have clarified. I used diamond blasts to search my raw reads for proteins homologs in BacMet...what I am really after is something that can take the gene count data per sample and create an abundance table for all samples...similar to an ORU table.
