### ISSUE TITLE
--setupdb error

### ISSUE THREAD

**Issue by michoug** [tseemann/abricate#77]
Hi,
I installed the tool via homebrew (v 0.8.10) and all the dependencies are installed.
When I run `abricate --setupdb` I got this error 

```
Removing old BLAST indices for /usr/local/Cellar/abricate/0.8.10/libexec/bin/../db/card/sequences
Making nucl BLAST index for /usr/local/Cellar/abricate/0.8.10/libexec/bin/../db/card/sequences
ERROR: Database card is not indexed, please try: abricate --setupdb
```
The sequences file exist but the indexes are not created.
When I run `makeblastdb -in /usr/local/Cellar/abricate/0.8.10/libexec/bin/../db/card/sequences -dbtype nucl` The database is created but there are some errors such as this one 

```
Bad char [0xB2] in string at byte 330
card~~~Klebsiella_pneumoniae_OmpK37~~~AJ011502.1:301-1426 Klebsiella pneumoniae outer membrane porin protein. Is preferentially detected in porin-deficient strains. Functional characterization of this new porin revealed a narrower pore than those of porins OmpK35 and OmpK36, which did not allow penetration by certain β-lactams. Also, when a resistant strain expresses porin OmpK37 is less susceptible to cefotaxime and cefoxitin than when it is expressing either OmpK36 or OmpK35.
Error: (803.7) [makeblastdb] Blast-def-line-set.E.title
Bad char [0xDF] in string at byte 54
card~~~OXA-424~~~KM588352:1-826 OXA-424 is a ?-lactamase found in clinical isolates of Acinetobacter baumannii found in China. It is carbapenem resistant.
Error: (803.7) [makeblastdb] Blast-def-line-set.E.title
Bad char [0xDF] in string at byte 54
card~~~OXA-425~~~KM588353:1-826 OXA-425 is a ?-lactamase found in clinical isolates of Acinetobacter baumannii. It is carbapenem-resistant
```

Any ideas?

**Comment by ealdraed** [comment]
I think it is a problem with non-ASCII characters in the descriptions. Try changing `β-lactams` to `beta-lactams` and the two occurences of `�-lactamase` to `beta-lactamase`. There might be two other `β` in KU961660 and AP009256 that have to be replaced.

**Comment by dswan** [comment]
I wonder if running things through https://metacpan.org/pod/Text::Unidecode or similar might be a plan, as I've had to previously manually fix this too.

**Comment by arpcard** [comment]
Errors at CARD noted, will be fixed.

**Comment by tseemann** [comment]
@arpcard the unicode chars are still not fixed, but i filed a new issue https://github.com/arpcard/amr_curation/issues/22
