### ISSUE TITLE
abricate-get_db --db card error

### ISSUE THREAD

**Issue by michoug** [tseemann/abricate#78]
Hi,
Following the issue [#77](https://github.com/tseemann/abricate/issues/77), I updated the card database using `abricate-get_db --db card` and got this error at the end

```
save_fasta: wrote 2237 sequences
Formatting BLASTN database: /usr/local/Cellar/abricate/0.8.10/libexec/db/card/sequences
file: /usr/local/Cellar/abricate/0.8.10/libexec/db/card/sequences.nin
file: /usr/local/Cellar/abricate/0.8.10/libexec/db/card/sequences.nhr
file: /usr/local/Cellar/abricate/0.8.10/libexec/db/card/sequences.nsq
file: /usr/local/Cellar/abricate/0.8.10/libexec/db/card/sequences.nsi
file: /usr/local/Cellar/abricate/0.8.10/libexec/db/card/sequences.nsd
file: /usr/local/Cellar/abricate/0.8.10/libexec/db/card/sequences.nhi
file: /usr/local/Cellar/abricate/0.8.10/libexec/db/card/sequences.nhd
file: /usr/local/Cellar/abricate/0.8.10/libexec/db/card/sequences.nog

BLAST Database creation error: Near line 326, the local id is too long.  Its length is 55 but the maximum allowed local id length is 50.  Please find and correct all local ids that are too long.
```

**Comment by fbreitwieser** [comment]
Got the same error with blast 2.8.1+. It's due to the `-parse_seqid` argument to `makeblastdb`. Don't think that abricate needs it.

**Comment by ealdraed** [comment]
I can confirm that it is BLAST+ 2.8.1 with the -parse_seqid that is causing this error. Without this argument or when running BLAST+ 2.7.1 the database is created fine.

**Comment by tseemann** [comment]
Thanks @ealdraed and @fbreitwieser !

**Comment by ealdraed** [comment]
Hello @tseemann !

If you remove the -parse_seqids flag there is later some redundancy in the product line, as it still contains `db~~~gene~~~accession `.

Maybe add something like `$hit{'stitle'} =~ s/$hit{'sseqid'} //; # remove subject SeqID from subject title` before [line 147](https://github.com/tseemann/abricate/blob/70b77850796e16fcceffdcf5bc8cc8caa331e961/bin/abricate#L147).

**Comment by tseemann** [comment]
@ealdraed is this still an issue?

**Comment by ealdraed** [comment]
@tseemann As I pointed out in my last post: By removing the `-parse_seqid` parameter the "Subject title" will contain a duplication of the "Subject sequence ID" (db~~~gene~~~accession), but adding the above code helped in getting rid of it. Maybe you come up with something better.

**Comment by tseemann** [comment]
I do not use `-parse-seqids` anymore and I don't seem to get duplicate IDs?

```
grep '>' db/card/sequences | cut -d ' ' -f 1 | sort | uniq -d
```
returns nothing?

**Comment by tseemann** [comment]
@ealdraed oh sorry I understand now! i have fixed this bug now:
https://github.com/tseemann/abricate/commit/849eb045c034797648972c2d2f63baa387f0873e

Thank you!

Oh i see what you are saying now!
