### ISSUE TITLE
ARG-ANNOT link no longer working

### ISSUE THREAD

**Issue by awitney** [tseemann/abricate#79]
Just FYI, the link to the ARG-ANNOT database seems to have gone away

**Comment by dswan** [comment]
It appears they've launched a new website. The arg-annot pages have been moved to a 'backup' server:

http://backup.mediterranee-infection.com/article.php?laref=282&titre=arg-annot

So the link referenced in abricate-get_db should be:

http://backup.mediterranee-infection.com/arkotheque/client/ihumed/_depot_arko/articles/691/argannot-nt_doc.fasta

However I note that this is the Dec 2015 release, and there appears to be a May 2018 release here?

http://backup.mediterranee-infection.com/arkotheque/client/ihumed/_depot_arko/articles/2042/arg-annot-v4-nt-may2018_doc.fasta

**Comment by dswan** [comment]
I've submitted a PR #81 for this

**Comment by sushim9** [comment]
New ARG-ANNOT link
https://www.mediterranee-infection.com/arg-annot/

**Comment by tseemann** [comment]
Fixed - thanks @sushim9 @dswan @awitney

**Comment by simonjuleseric2** [comment]
The "new" links is not working either. For example, the tutorial link points to a non-existent page.

**Comment by sushim9** [comment]
https://www.mediterranee-infection.com/acces-ressources/base-de-donnees/arg-annot-2/

*Sushim Kumar Gupta*
*USDA-ARS*
*Athens*
*GA-30605*
