### ISSUE TITLE
Install also requires BioPerl

### ISSUE THREAD

**Issue by kblin** [tseemann/abricate#8]
When installing via `brew`, the installation aborts complaining about BioPerl not being installed. You might want to add this to the dependencies?

**Comment by kblin** [comment]
Ah, never mind, after I RTFMed homebrew docs, I realize that they decided to not support stuff you can grab off CPAN. Curious decision, as they do provide stuff you can grab off PyPi, and installing locally into a Python virtualenv feels easier than figuring out local CPAN installs, but whatever. Not an abricate issue.

**Comment by tseemann** [comment]
Yeah - i wish I could bundle CPAN stuff. You can sort of do it manually but it's something very annoying. I often use it only for FASTA/GBK loading (just sequence) so I might write a simple module to do it I can bundle.  

Or as many suggest, I should switch to Python :)
