### ISSUE TITLE
Add orientation of hit to results?

### ISSUE THREAD

**Issue by thsyd** [tseemann/abricate#83]
Hi,
Can I suggest to include an option to include the orientation of a resistance gene hit in the results? eg plus/minus or complement?

As a use case, I am using abricate to identify resistance genes and IS elements in Bacteroides speceis. Here the expression of a metallo-betalactamase (CfiA / ccrA) is partially dependant on an IS element upstream (but on the complement strand) of the metallo-betalactamase gene, as the IS elements harbor sequences that act as promoters.
The same is probably true for the possible metronidazole-resistance genes (nim-family).

Below is an example of a hit for nimD and an IS element. If the nimD gene is in fact on the complement strand, then the IS element is "upstream" of the nimD-gene. This is not apparant from what is included in the abricate results at the moment.

```
#FILE	SEQUENCE	START	END	GENE	COVERAGE	COVERAGE_MAP	GAPS	%COVERAGE	%IDENTITY	DATABASE	ACCESSION	PRODUCT
BFO18assembly.fasta	2	2215	2709	nimD	1-495/495	===============	0/0	100.00	99.19	ncbi	A7J11_00718	nitroimidazole resistance protein NimD
BFO18assembly.fasta	2	2718	4028	IS1169_IS5_IS5	4-1317/1317	========/======	2/3	99.54	99.31	IS-finder		N/A
```

**Comment by thsyd** [comment]
So, I've managed to create an interim solution that I can use by commenting out line 131 in the current version of https://raw.githubusercontent.com/tseemann/abricate/master/bin/abricate

```
 # ($hit{sstart}, $hit{send}) = ($hit{send}, $hit{sstart}) if $hit{sstrand} eq 'minus';
```
This results in the COVERAGE column reversing the nucleotides of the hit (and the COVERAGE_MAP showing no coverage).

e.g here you can see that for the second line, the hit (IS613...) was on the complement strand.
```

#FILE	SEQUENCE	START	END	GENE	COVERAGE	COVERAGE_MAP	GAPS	%COVERAGE	%IDENTITY	DATABASE	ACCESSION	PRODUCT
assembly.fasta	1	486315	487909	IS613_IS1380_IS942	1-1595/1595	===============	0/0	100.00	100.00	abricate_tvs		N/A
assembly.fasta	1	661872	663466	IS613_IS1380_IS942	1595-1/1595	...............	0/0	100.00	100.00	abricate_tvs		N/A


```

**Comment by tseemann** [comment]
I think having `STRAND` column is a good idea. I will add it.

**Comment by tseemann** [comment]
Added in 62cfa6a8f07ea8b8fdcef8ebfb42710eb9845ea5
