### ISSUE TITLE
option --nopath seems not be working together with --summary

### ISSUE THREAD

**Issue by eneasdecarvalho** [tseemann/abricate#84]
Hi,

     This seems to be a simple issue. The option --nopath seems not be working together with --summary.

best regards,
Eneas

**Comment by msevi** [comment]
Ran with and without the --nopath flag on Abricate v 0.8.13 and my output is the same in both instances. 

Output head:
#FILE   NUM_FOUND
co_1.out2.resfinder     1       ;;;;;;;;;
co_2.out2.resfinder     1       ;;;;;;;;;;;;;;
co_3.out2.resfinder     1       ;;;;;;;;;;;;;;;;;;;
co_4.out2.resfinder     1       ;;;;;;;;;;;;;;;;;
co_5.out2.resfinder     1       ;;;;;;;;;;;;;;;;;;
co_6.out2.resfinder     1       ;;;;;;;;
co_7.out2.resfinder     1       ;;;;;;;;;;;;;;;;;;;;;;;;;;;;
co_8.out2.resfinder     1       ;;;;;;;;;;;;;;;;;;;
co_9.out2.resfinder     1       ;;;

**Comment by tseemann** [comment]
The `--summary` option is a bit of a hack - i will looking it.

**Comment by tseemann** [comment]
@eneasdecarvalho @msevi there was indeed a bug - in `--summary` it was removing the path from the FILE column in each file but that was not used, I needed to remove it in the actual _summary_ filename you are summaring. I've fixed and will release in 0.9.8. Thank you!

**Comment by eneasdecarvalho** [comment]
Thank you!
