### ISSUE TITLE
abricate: trouble updating card, argannot, vfdb databases

### ISSUE THREAD

**Issue by nadinevogt21** [tseemann/abricate#87]
Hi there,

I'm new to programming, so forgive me if I have overlooked something basic...

Trying to update card, argannot and vfdb databases in abricate, and getting different error messages for each: 

**(abricate) Nadines-MacBook-Pro:~ nadinevogt$ abricate-get_db --db card --force**
Setting up 'card' in '/Users/nadinevogt/miniconda3/envs/abricate/db/card'
Downloading: https://card.mcmaster.ca/download/0/broadstreet-v1.1.8.tar.gz
Result: 500
Destination: card.tar.bz2
Filesize:  bytes
tar: Error opening archive: Failed to open 'card.tar.bz2'
read_file './card.json' - open: No such file or directory at /Users/nadinevogt/miniconda3/envs/abricate/bin/abricate-get_db line 214.

**(abricate) Nadines-MacBook-Pro:~ nadinevogt$ abricate-get_db --db vfdb --force**
Setting up 'vfdb' in '/Users/nadinevogt/miniconda3/envs/abricate/db/vfdb'
Downloading: http://www.mgc.ac.cn/VFs/Down/VFDB_setA_nt.fas.gz
Result: 304
Destination: vfdb.fa.gz
Filesize: 1326424 bytes
load_fasta: vfdb.fa
load_fasta: read 3204 sequences
BLAST options error: /Users/nadinevogt/miniconda3/envs/abricate/db/vfdb/sequences does not match input format type, default input type is FASTA
Building a new DB, current time: 04/17/2019 11:19:14
New DB name:   /Users/nadinevogt/miniconda3/envs/abricate/db/vfdb/sequences
New DB title:  vfdb
Sequence type: Nucleotide
Keep MBits: T
Maximum file size: 1000000000B
BLAST options error: /Users/nadinevogt/miniconda3/envs/abricate/db/vfdb/sequences does not match input format type, default input type is FASTA
ERROR: Error with makign BLAST database. See /Users/nadinevogt/miniconda3/envs/abricate/db/vfdb/src/makeblastdb.log

**(abricate) Nadines-MacBook-Pro:~ nadinevogt$ abricate-get_db --db argannot --force**
Setting up 'argannot' in '/Users/nadinevogt/miniconda3/envs/abricate/db/argannot'
Downloading: http://www.mediterranee-infection.com/arkotheque/client/ihumed/_depot_arko/articles/1425/argannot-aa-v3-march2017_doc.fasta
Result: 404
Destination: arg-annot.fa
Filesize:  bytes
edit_file 'arg-annot.fa' - read_file: No such file or directory at /Users/nadinevogt/miniconda3/envs/abricate/bin/abricate-get_db line 186.

The only change I made to the **abricate-get_db** file was from a previous issue with duplicate sequence ids in the vfdb database (issue #64). 

Thanks in advance!

Nadine

P.S. No issues updating resfinder, plasmidfinder or ncbibetalactamase databases...

**Comment by tseemann** [comment]
You seem to be using an old version of abricate?
Can you tell me what `abricate --version` says?

**Comment by nadinevogt21** [comment]
Thanks for the quick reply! Yes, you're right---my version is way outdated (0.5)!

I used the following command to download abricate:

•	Conda create -n abricate -c bioconda abricate

Wondering how I can get the latest version while creating an environment? 

Thanks!
Nadine

**Comment by tseemann** [comment]
@nadinevogt21 

The correct channel order is this:

 conda create -n abricate -c conda-forge -c bioconda -c defaults abricate
```
