### ISSUE TITLE
'file' does not exist, or is unreadable

### ISSUE THREAD

**Issue by gopel** [tseemann/abricate#88]
Hi,

When I try to use Abricate, I come across a weird error notification : `WARNING: 'file' does not exist, or is unreadable`.  
I always give the absolute path to the file, so I believed that the file is unreadable. 
I tried to use Abricate on several computers, with different installations (on the laptop or on a Docker image), and I still have the error.  
I tried on genomes assembled with Spades and genomes downloaded on the NCBI database, and the result is the same.   
For instance, here is the result of my last run (the file is join in .txt, but I used it in .fna, I downloaded it from the NCBI database) :
```
Using database resfinder:  2228 sequences -  2017-Aug-31
Processing: GCF_000005845.fna
WARNING: 'GCF_000005845.fna' does not exist, or is unreadable
#FILE	SEQUENCE	START	END	GENE	COVERAGE	COVERAGE_MAP	GAPS	%COVERAGE	%IDENTITY	DATABASE	ACCESSION
```
Could you help me please?

Best regards,

Yanis

**Comment by tseemann** [comment]
@gopel which version are you using?   (type `abricate --version`)

**Comment by gopel** [comment]
Hi,
1. It's the version ```0.8.13```.
2. It says : ```9184 -rw-r--r--@ 1 yanis  staff  4699745 Apr 25 15:06 /Users/yanis/Downloads/GCF_000005845.fna```

**Comment by gopel** [comment]
Hi,

  I am sorry to insist, but do you have any new regarding this issue please?

  Thank you in advance.

  Best regards,

  Yanis

**Comment by dswan** [comment]
I don't understand how `ls -lsa` gives you the path to your file, if the file is not in your current working directory this will just fail with "No such file or directory". If you're specifying the location of your file for the `ls `command to work are you also specifying the full path when running abricate? 

`abricate --db resfinder /Users/yanis/Downloads/GCF_000005845.fna`

There's nothing inherently wrong with this version of abricate, or this file (I have the same file downloaded) so it looks like this is something wrong with the invocation.

**Comment by gopel** [comment]
Thank you. I will try that when I get my own computer back :)

**Comment by tseemann** [comment]
Assuming you are the use `yanis` it should work if you do what @dswan says.
If not, you will need to make sure `/Users/yanis` and `/Users/yanis/Downloads` are both `chmod a+rx`
