### ISSUE TITLE
Full power of Abricate

### ISSUE THREAD

**Issue by MichWeb75** [tseemann/abricate#89]
Hi, I like the simplicity of Abricate very much and I am wondering how to use it in a smart way to reduce false negative hits.
For example _Mycoplasma bovis_, cattle outbreak isolate PG45. If you choose to run the reference sequence against VFDB
`abricate --db vfdb NC_014760.fna  --minid 40 --mincov 50`
0 Results

However when I do **blastx** of VFDB against the translated coding sequences of PG45, four hits come up: ccmA, ctrD, hasC, mgtB.

My question is it reasonable to move from nucleotide to protein sequences to at least report the presence of the virulence protein even if it is not the copy of the database. And how to achieve this in abricate ?
Best, Michael

**Comment by tseemann** [comment]
I have experimental tblastx support in abricate BUT it is _extremely_ slow beacause it is the wrong way around in terms of query and database.

**Comment by tseemann** [comment]
@MichWeb75 i recommend you use AMRFinderPlus - it now has good curated databases including stress, AMR, metal, and virulence. And it uses protein matching.

https://github.com/ncbi/amr/wiki
