### ISSUE TITLE
Output 'antibiotic class' in the TSV

### ISSUE THREAD

**Issue by tseemann** [tseemann/abricate#9]

**Comment by tseemann** [comment]
Only resfinder, and maybe CARD have this information?

**Comment by bachev** [comment]
May I propose "MEGARes" as additional database which contains this kind of info?

https://megares.meglab.org/download/index.php

Also has interesting additional info like "RequiresSNPConfirmation"

**Comment by tseemann** [comment]
@bachev I do not like MEGAres. My code has ability to download it, but I do not trust the curation they claimed they did.   I think they simply ran `cd-hit-est` on the 3 DB. The corresponding author is on leave for a year.

**Comment by viehwegerlib** [comment]
Are there any updates on the MEGARes issue? Thank you.

**Comment by fbreitwieser** [comment]
Hi Torsten, I've a modified abricate version that pulls in the AMR class for resfinder. CARD support should be possible, too.

It's done the following way:
**DB build**
  - The class name is parsed from the resfinder file name, e.g. macrolide, phenicol, etc. It has no spaces, and is noteds in a `$seq->{CLASS}` hash.
  - `dedupe_seq` merges the `CLASS` fields of the sequences it encounters
  - The IDs get an additional field separated by `~~~` that starts with `CLASS:` and has the classes separated by colons. E.g.
```
>resfinder~~~cfr_1~~~AM408573~~~CLASS:macrolide:oxazolidinone:phenicol cfr_1
```

**Search**
  - I added the option `--extracolumns`, which basically just adds a column `CLASS` after `GENE`, and prints the class when available.

Let me know your thoughts. If you are interested, I'll push it to Github after a bit of further testing and make a pull request.

**Comment by apredeus** [comment]
Any updates on this? What is the best way to predict resistance to a certain antibiotic, after we have a reasonably reliable collection of predicted AMR genes? 

As always, thank you for any suggestions!

**Comment by agmcarthur** [comment]
CARD provides classification at the Drug Class, Resistance Mechanism, and AMR Gene Family level. Individual MICs (gene -> antibiotic) is in progress, but incomplete.

**Comment by apredeus** [comment]
Thank you. I've found their command line tool (RIG), looking for the best way to apply it.

**Comment by tseemann** [comment]
I've added a `RESISTANCE` column.
Populated for CARD, NCBI and Resfinder.
