### ISSUE TITLE
Db update problems

### ISSUE THREAD

**Issue by jacarrico** [tseemann/abricate#90]
Greetings...several databases are not currently updating:

**CARD**
Card filename changed to https://card.mcmaster.ca/latest/data/card-data.tar.bz2

**NCBI**

> $ abricate-get_db --db ncbi --force
Setting up 'ncbi' in '/usr/local/Cellar/abricate/0.8.13/libexec/db/ncbi'
Running: esearch -db nucleotide -query '313047[BioProject]' | efetch -db nuccore -format gbwithparts
sh: esearch: command not found
sh: efetch: command not found
dedupe_seq: read 0 / kept 0
Sorting sequences by ID
save_fasta: /usr/local/Cellar/abricate/0.8.13/libexec/db/ncbi/sequences
save_fasta: wrote 0 sequences
Formatting BLASTN database: /usr/local/Cellar/abricate/0.8.13/libexec/db/ncbi/sequences

>Building a new DB, current time: 05/21/2019 17:19:15
New DB name:   /usr/local/Cellar/abricate/0.8.13/libexec/db/ncbi/sequences
New DB title:  ncbi
Sequence type: Nucleotide
Deleted existing Nucleotide BLAST database named /usr/local/Cellar/abricate/0.8.13/libexec/db/ncbi/sequences
Keep MBits: T
Maximum file size: 1000000000B
BLAST options error: File /usr/local/Cellar/abricate/0.8.13/libexec/db/ncbi/sequences is empty
ERROR: Error with makign BLAST database. See /usr/local/Cellar/abricate/0.8.13/libexec/db/ncbi/src/makeblastdb.log

This also breaks the `abricate --list` since it starts complaining that it needs the `--setupdb` and when using the option still reports `ERROR: Database ncbi is not indexed, please try: abricate --setupdb` 

**Arg-Annot**

The fasta file also moved ...

>Setting up 'argannot' in '/usr/local/Cellar/abricate/0.8.13/libexec/db/argannot'
Downloading: http://www.mediterranee-infection.com/arkotheque/client/ihumed/_depot_arko/articles/691/argannot-nt_doc.fasta
Result: 404
Destination: arg-annot.fa
Filesize:  bytes
Error open (<) on 'arg-annot.fa': No such file or directory at /usr/local/Cellar/abricate/0.8.13/libexec/bin/abricate-get_db line 298.

**Comment by tseemann** [comment]
1. CARD

I can not replicate this issue. The plain URL ending in `data/` redirects to the correct one.

2. NCBI

You need to have `eftech` installed. There is no brew package. is there a conda one?

3. ARG-ANNOT

The  website has not moved, it is gone forever. I need to find an alternate home.

**Comment by arpcard** [comment]
CARD confirms that https://card.mcmaster.ca/latest/data is working properly.

**Comment by tseemann** [comment]
Thanks @arpcard  :)

**Comment by munchee13** [comment]
This is still failing for card for me on a MacOS (installed abricate with brew):
$abricate-get_db --db=card
Setting up 'card' in '/usr/local/Cellar/abricate/0.8.13/libexec/db/card'
Downloading: https://card.mcmaster.ca/latest/data
Result: 500
Destination: card.tar.bz2
Filesize:  bytes
tar: Error opening archive: Failed to open 'card.tar.bz2'
ERROR: Problem with tar xf card.tar.bz2 ./card.json

**Comment by tseemann** [comment]
@munchee13 are you
`Filesize: bytes` suggests the file didn't download at all - it is missing a numerical count of the number of bytes.

Can you make this change to the script?
```
-     'https://card.mcmaster.ca/latest/data',
+    #'https://card.mcmaster.ca/latest/data/card-data.tar.bz2',
```

**Comment by jacarrico** [comment]
@tseemann what @munchee13 reports is what I had as error. It says failed to open "card.tar.bz2" and the new one is "card-data.tar.bz2"

**Comment by tseemann** [comment]
This is fixed.
