### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by macgenomegue** [tseemann/abricate#93]
Hi,
I was wondering if you have ever encountered this issue...
It was working perfectly before but since I've updated to the version 0.8.13 on mac os I can't run abricate anymore.

$ abricate
Segmentation fault: 11

Do you have any suggestions?
Best,
Guero

**Comment by tseemann** [comment]
Abricate is essentially just Perl and BLAST+, so one of those must be causing the segfault.  But given you get the segfault immediately after running `abricate`, it suggests your Perl is corrupt?

How did you install abricate?

**Comment by macgenomegue** [comment]
> Abricate is essentially just Perl and BLAST+, so one of those must be causing the segfault. But given you get the segfault immediately after running `abricate`, it suggests your Perl is corrupt?
> 
> How did you install abricate?

Sorry for the dayed reply.
I've installed again perl and now everything works... It was definitely corrupted
