### ISSUE TITLE
Filtering relevant hits

### ISSUE THREAD

**Issue by AroArz** [tseemann/abricate#94]
Hi!

Recently used abricate on my assembly contigs and I've got some (amateur level) questions if you dont mind.

1. Using `abricate --list` how does the number of sequences in vfdb fall below those available in ecoli_vf?
2. Is the screening on nucleotide level?
3. I've got a lot of hits in the databases and have difficulties filtering relevant hits. Do you have any guidance as to how reflect regarding Coverage, Coverage% and Identity% to filter relevant hits?

I appreciate any help

**Comment by tseemann** [comment]
1. They are different databases?

http://www.mgc.ac.cn/VFs/Down/VFDB_setA_nt.fas.gz
https://github.com/phac-nml/ecoli_vf/raw/master/data/repaired_ecoli_vfs_shortnames.ffn

2. Yes, DNA:DNA matching

3. No, it's application dependent. I try to provide some sensible defaults, but it all depends on the scientific question you are asking.

**Comment by AroArz** [comment]
I was under the impression vfdb would include the majority of virulence genes present in ecoli_vf in addition to virulence genes from other species and hence surpass ecoli_vf in number of sequences based on https://github.com/phac-nml/ecoli_vf . 

Thanks for providing some clarity.

**Comment by tseemann** [comment]
Some of these databases are old or unmaintained, and the curators may have different ideas about what a virulence gene is.
