### ISSUE TITLE
Abricate stuck processing file with special character in fasta header!

### ISSUE THREAD

**Issue by mmaesaar** [tseemann/abricate#99]
I was running abricate using following command:
`abricate --db argannot --threads 7 *.fas > argannot2.tab`

abricate got several times stuck when processing certain file  and it seems like the problem is with character "|" in fasta header.

**Comment by tseemann** [comment]
What does "stuck" mean?
What does `abricate --version` say?
Can you attach the file here?
Or at least the FASTA headers?  eg. `grep '>' *.fas`

**Comment by mmaesaar** [comment]
With stuck I mean abricate outputs `Processing: 58163_ARI3989.fas` and nothing happens no progress. In Activity Monitor blastn %CPU is 0,0

Fasta header is `>scaffold21|size539`. When `|` is removed abricate finishes with no problems.

**Comment by tseemann** [comment]
I can't reproduce this issue. I get contig names with `|` and it works. Maybe try 0.9.7 ?

**Comment by nbawe** [comment]
0.9.7 works with no issues

**Comment by tseemann** [comment]
Thanks for the external confirmation @nbawe
